### ISSUE TITLE
Upgrade to log4net 1.2.13

### ISSUE THREAD

**Issue by cpoyraz** [castleproject/Core#109]
Hi,
Is it possible to upgrade lognet with last version in nuget?

Thank you.

**Comment by jonorossi** [comment]
Hi @cpoyraz, we've looked at this in the last 12 months and found there are breaking changes between 1.2.10 and 1.2.11+ other than the strong name key changing, see https://github.com/castleproject/Core/pull/53#issuecomment-82291726 for more details.

However since we are working towards the next major release of Castle Core which will support .NET Core I'm definitely open to bumping our supported log4net version to 1.2.13 (2.0.3 on NuGet.org), which would drop support for 1.2.10. It is very likely that the log4net guys will need to release again with changes to support .NET Core since so much is missing (https://issues.apache.org/jira/browse/LOG4NET-467).

**Comment by cpoyraz** [comment]
I am looking forward to that release.
Thank you.

**Comment by bakgerman** [comment]
Is it possible to upgrade to log4net 2.0.5 (which is actually log4net 1.2.15)?
It seems due to issues on the log4net side this may not be possible, or at the very least may require a whole separate build of caste.core-log4net (which also means not really possible).

**Comment by jonorossi** [comment]
@bakgerman yes to 1.2.15, we'll upgrade to the newest version before releasing Castle Core v4 even if log4net does not have .NET Core support at that time.

**Comment by jonorossi** [comment]
log4net has been upgraded to 1.2.15 in #199, it'll be released with Castle Core 4.0 very soon.
