### ISSUE TITLE
NSubstitute using Castle.DynamicProxy initial mock creation slow

### ISSUE THREAD

**Issue by informatorius** [castleproject/Core#114]
I made an issue at NSubstitute because initial mock creation is slow.
https://github.com/nsubstitute/NSubstitute/issues/206
They found that 50% of time is spent in Castle.DynamicProxy.
Is there something you can do in Castle.DynamicProxy to speed things up?

This is the profiler callstack details:
![initialmockperformance_profiler_details](https://cloud.githubusercontent.com/assets/6989214/10483474/f928bb76-727f-11e5-9ba8-36ee295703c8.PNG)

**Comment by stakx** [comment]
I think we can close this issue. Objections, anyone?

We have been waiting for nearly three years for a repro for the claim "*initial* mock creation slow", doesn't look like that is still coming. 😃 Apart from that, there's no specific request here other than, "Is it possible to optimize DynamicProxy?"

Regarding that latter question, optimizing DynamicProxy is currently almost impossible because so much of its internals are publicly exposed, so any real changes very quickly end up being breaking changes (which we're trying to avoid). We need to first reduce the public API surface (see #389) to gain the wiggle room necessary for tuning and refactoring DP's internals.

(Even if and when that happens, I wouldn't get my hopes up too much: There might be some efficiency gains here and there, but the most expensive part is likely System.Reflection.Emit, and there's no way around it, given DynamicProxy's current architecture.)

**Comment by informatorius** [comment]
Did not see the "needs-repro" request. Maybe I try it tomorrow if it is still reproducable and if not will close this.

**Comment by stakx** [comment]
I'll close this issue for now, as it is getting rather stale. :-) @informatorius, if you do come up with a repro eventually, just post again here, and we'll reopen the issue.
