### ISSUE TITLE
A COM type can't make its proxy by same procedure as usual.

### ISSUE THREAD

**Issue by urasandesu** [castleproject/Core#117]
This issue is related from [Moq4#215](https://github.com/Moq/moq4/issues/215). In Castle.Core 3.3.3, it will throw `MissingMethodException` even if the default implementation is automatically generated against a managed type. For example, the product code is the below: 
```cs
namespace ClassLibrary1
{
    public class Class1
    {
        private Project m_proj;

        public Class1(Project proj)
        {
            m_proj = proj;
        }

        public string Foo()
        {
            return m_proj.Name;
        }
    }
}
```

**NOTE:** `Project` is a COM type in [Microsoft Development Environment](https://msdn.microsoft.com/en-us/library/envdte.project.aspx).

The test code is the below: 
```cs
namespace ClassLibrary1Test
{
    [TestFixture]
    public class Class1Test
    {
        [Test]
        public void Foo_should_return_null()
        {
            // Arrange
            var generator = new ProxyGenerator();
            var proxy = generator.CreateInterfaceProxyWithoutTarget<Project>(new MyInterceptor());
            var class1 = new Class1(proxy);

            // Act
            var result = class1.Foo();

            // Assert
            Assert.IsNull(result);
        }

        class MyInterceptor : IInterceptor
        {
            public void Intercept(IInvocation invocation)
            {
                if (invocation.Method.Name == "get_Name")
                    invocation.ReturnValue = null;
                else
                    throw new NotImplementedException();
            }
        }
    }
}
```

When running the test, I got the following results: 
```powershell
PM> .\packages\nunit.Runners.2.6.4\tools\nunit-console.exe .\ClassLibrary1Test\bin\Debug\ClassLibrary1Test.dll /framework:v4.5
NUnit-Console version 2.6.4.14350
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment - 
   OS Version: Microsoft Windows NT 6.2.9200.0
  CLR Version: 2.0.50727.8000 ( Net 3.5 )

ProcessModel: Default    DomainUsage: Single
Execution Runtime: v4.5
.F
Tests run: 1, Errors: 1, Failures: 0, Inconclusive: 0, Time: 1.039795 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0

Errors and Failures:
1) Test Error : ClassLibrary1Test.Class1Test.Foo_should_return_null
   System.MissingMethodException : Error: Missing method 'instance string [ClassLibrary1] EnvDTE.Project::get_Name()' from class 'Castle.Proxies.ProjectProxy'.
   at EnvDTE.Project.get_Name()
   at ClassLibrary1.Class1.Foo() in c:\Users\Akira\Documents\Visual Studio 2013\Projects\ClassLibrary1\ClassLibrary1\Class1.cs:line 21
   at ClassLibrary1Test.Class1Test.Foo_should_return_null() in c:\Users\Akira\Documents\Visual Studio 2013\Projects\ClassLibrary1\ClassLibrary1Test\Class1.cs:line 26


```

Is this a bug? Or, does DynamicProxy manage a COM type by special way?(It is the limitation by the design?)

**Comment by jonorossi** [comment]
I just tried to reproduce your sample project but the unit test passes with nunit-console, nunit-console-x86 and with ReSharper.

We do have [unit tests for COM interfaces](https://github.com/castleproject/Core/blob/master/src/Castle.Core.Tests/ComInterfacesTests.cs) because there are a few differences.

Can you try changing your unit test to this and open up `CastleDynProxy2.dll` with something like dotPeek or ildasm to see if the `ProjectProxy` class has an implementation for the Name property:
```csharp
PersistentProxyBuilder builder = new PersistentProxyBuilder();
builder.CreateInterfaceProxyTypeWithoutTarget(typeof(Project), Type.EmptyTypes, ProxyGenerationOptions.Default);
builder.SaveAssembly();
```

**Comment by urasandesu** [comment]
I tried your suggestion, and I placed the results to my shareable Google Drive: 

* CastleDynProxy2.dll.dasm - Google Drive
https://drive.google.com/open?id=0B4s_gXgDJAgbZDJoNVd0WFBrNmM
This is the disassembled result of `CastleDynProxy2.dll` by ildasm. It seems that `Name` property(`get_Name` method) doesn't exist.

* CastleDynProxy2.dll - Google Drive
https://drive.google.com/file/d/0B4s_gXgDJAgbblBwdnRnWVpFTmM
This is the generated assembly.

* ClassLibrary1.zip - Google Drive
https://drive.google.com/file/d/0B4s_gXgDJAgbelRqck5GQkk5dmM
For your information, I also placed original `ClassLibrary1.sln`.

**Comment by jonorossi** [comment]
@urasandesu I just had a quick look at your sample, it fails for me too. When I created my sample I did the unit test in the same project and that works.

The reason it is failing is because `GetProperties` doesn't return the `Name` property, it actually returns no properties, `GetProperties` is used here in DP:
https://github.com/castleproject/Core/blob/master/src/Castle.Core/DynamicProxy/Contributors/MembersCollector.cs#L85

I don't know what the .NET runtime does to import type libraries via COM, however it seems to only have the properties being used available for reflection, see the sample below where `GetProperties` will only return the properties that are used in the code. From a quick Google search I didn't find any info on how this works and why it doesn't work when the property is being used in another assembly.

```csharp
public class Class1Test
{
    [Test]
    public void Foo_should_return_null()
    {
        var propertyInfos = typeof(Project).GetProperties();
        Assert.AreEqual(2, propertyInfos.Length);
    }

    public void A(Project p)
    {
        string name = p.Name;
        string kind = p.Kind;
    }
}
```

Could you do some research into .NET, COM and reflection to see if you can find the reason? There isn't much DynamicProxy can do if the runtime won't give us the metadata.

**Comment by urasandesu** [comment]
I researched about COM interop and I found the reason!! (and now, it turns out that I made a mistake in my project setup...:fearful:)

The reason for this issue is that `Embed Interop Types` project property was **true**:
![01 embedinteroptypeswastrue](https://cloud.githubusercontent.com/assets/291065/11351087/ff9c3a2e-9277-11e5-8d5b-0db659498bf9.png)

[As Scott Hanselman explained in his blog](http://www.hanselman.com/blog/CLRAndDLRAndBCLOhMyWhirlwindTourAroundNET4AndVisualStudio2010Beta1.aspx), "Just the types I was using are now embedded within my application" if the property is set to true. Also, this affects against the properties, too.

Now, everything has gone well by changing the property to **false** :joy:
Thank you very much for your hint!!
