### ISSUE TITLE
Fix SerilogFactory to accept an ILogger rather than a LoggerConfiguration

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#142]
See https://github.com/serilog/serilog/issues/561#issuecomment-189552136 and following comments for more details.

**Comment by jonorossi** [comment]
@IanYates @nblumhardt just so you guys are aware this is likely going to get pushed out of 4.0 because of the pressures to release 4.0 and my limited time. After using Serilog on a project recently I see how the current factory is broken. I'll take a look at it on the weekend and see if I can rework it, however if you've got time I'd love a PR.

**Comment by IanYates** [comment]
I'll see what I can do for a pr once end of financial year stuff is done (got a few projects on the boil for the next few days )

Cheers, Ian

Ian Yates
Medical IT
+61 7 3117 0956



On Wed, Jun 29, 2016 at 1:18 PM +1000, "Jonathon Rossi" <notifications@github.com<mailto:notifications@github.com>> wrote:


@IanYates<https://github.com/IanYates> @nblumhardt<https://github.com/nblumhardt> just so you guys are aware this is likely going to get pushed out of 4.0 because of the pressures to release 4.0 and my limited time. After using Serilog on a project recently I see how the current factory is broken. I'll take a look at it on the weekend and see if I can rework it, however if you've got time I'd love a PR.

-

**Comment by jonorossi** [comment]
@IanYates I'd be great if you could review the Serilog integration now after I've reworked it to see if there are any other problems.
