### ISSUE TITLE
Nuget package with PCL is not available

### ISSUE THREAD

**Issue by godrose** [castleproject/Core#162]
I'd like to use castel.core in portable/universal apps projects.
The available nuget package does not contain the required assemblies.

**Comment by jonorossi** [comment]
UWP doesn't support `System.Reflection.Emit` because it uses .NET Native, so DynamicProxy isn't possible on the UWP:
* https://msdn.microsoft.com/en-us/library/mt185483.aspx
* https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/8280606-windows-10-uwp-should-support-reflection-emit-for
* https://twitter.com/nguerrera/status/662167030741663744

We are working on .NET Core support which will provide support for the [.NET Platform Standard v1.3](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms) which will allow you to write and run your unit tests in a separate class library and consume the code with your UWP project.
