### ISSUE TITLE
Improve Mono on Windows build

### ISSUE THREAD

**Issue by blairconrad** [castleproject/Core#169]
This may be completely selfish, as I'm not sure if "Mono on Windows" is something that we really care about. I only bring it up because I installed Mono. On Windows. In order to make sure that .NET Core changes don't break Mono. And I find building/testing inconvenient.

First, the `build.cmd` script doesn't support Mono. `build MONO` fails miserably. I think this is an easy fix, if you're interested.

Second, if I run the [command specified in the README](https://github.com/castleproject/Core#mono):
```
xbuild /p:Configuration=NET45-Release /t:RunAllTests buildscripts/Build.proj
```

then the compilation works fine, but the test-running falls down because the value of `$(TestAssemblies)` is lost between the `BuildProject` target and the `_ExecTestRunner` target. The property still has the correct value in `RunAllTests`, though, which invokes `_ExecTestRunner` via a `CallTarget`. `RunAllTests` depends on `BuildProject`.

I do not understand the property scoping rules or why `xbuild` would behave differently in this regard when on Windows versus on Linux (or when compared to MSBuild), but changing the `CallTarget`s to `DependsOnTargets`es seems to do the trick.
Unless you completely hate this approach (or the whole issue), I'll send a PR for consideration.

**Comment by jonorossi** [comment]
I didn't even realise the Mono Project was shipping Windows builds anymore, I recall talk on the development mailing list that no one really uses it. Knowing now that they do actually ship Windows binaries I don't have a problem adding this to build.cmd.

xbuild has all sorts of differences in behaviour because it has a subset of functionality and implements things differently with much of that msbuild behaviour likely undocumented.

**Comment by jonorossi** [comment]
Merged

**Comment by blairconrad** [comment]
> no one really uses it

I probably should've set up a Linux VM and mounted the directory and built from there, but I was lazy…
