### ISSUE TITLE
.NET Core - include the NETCORE build in the NuGet package

### ISSUE THREAD

**Issue by blairconrad** [castleproject/Core#171]
The CI server produces .dll, .pdb, and .xml files as artifacts. Why not pack 'em into the regular NuGet package? That might save time and effort [for downstream folk who are trying to work on a .NET Core build](https://github.com/FakeItEasy/FakeItEasy/pull/617#issuecomment-189585406).

@jonorossi, there's no "unofficial" nupkg feed for interim builds, is there? Would consumers just have to grab .nupkgs from the CI server?

**Comment by adamralph** [comment]
:+1: 

BTW - it's not just NETCORE. Building for NET40 doesn't produce a package either.

**Comment by blairconrad** [comment]
@adamralph, it's no the "build" command that makes the package. There's a separate TeamCity build configuration that eats up the output of all the other builds (except NETCORE right now) and packs them together. We'd have to amend it to suck up NETCORE. The title of this issue is misleading. Will amend.

**Comment by adamralph** [comment]
OK. It would be good if the command line build could produce packages too.

**Comment by blairconrad** [comment]
@jonorossi, I know that the mono build on the netcore branch isn't stable. Perhaps we could exclude it at first?

**Comment by blairconrad** [comment]
@adamralph, indeed, but might be a significant departure from the way the Castle.Core project builds. Currently, each of the framework versions is built via a separate build configuration on the CI server, and the "pack" configuration sucks things up. Each of the first build configurations does the equivalent of running `build FRAMEWORK`.
We'd have to introduce a coordinating task that would run all the framework builds in turn (which may be tricky for the MONO build, although I've had recent success with MONO for Windows) and then package.

I'm not saying it's a bad idea, but new and different. And probably best as a separate issue.

**Comment by jonorossi** [comment]
> I know that the mono build on the netcore branch isn't stable. Perhaps we could exclude it at first?
The Mono build should never be packaged, it is only there for testing/verification purposes. Once Mono is using Roslyn I'd like this build to just be a unit test run using the NET45 output. Just ignore that build for now.

> indeed, but might be a significant departure from the way the Castle.Core project builds.
Yes, and it is something I've been waiting to see if #134 will fix. I've been waiting for //BUILD/ for Microsoft to release DNX/CLI RC2 so we can move forward rather than setting up stuff with dnu that is all going to break. Since we no longer support Silverlight that is two configurations that we no longer need to hack around, so now left with only 4 (3.5, 4.0, 4.5, Core) I was hoping the new tools would allow us to build, test and pack everything easily in a single TeamCity configuration without the need for heaps of TeamCity build steps, adding another layer to the build scripts or the separate "Pack" configuration we have today.

**Comment by jonorossi** [comment]
@blairconrad I also was going to mention that I put this exact item on my TODO list to look at this weekend when I hoped to see RC2 out because I want to get an alpha.1 package out.

**Comment by igatanasov** [comment]
Hi guys,

where is the .net core nuget package feed so I can download it?

**Comment by jonorossi** [comment]
> Hi guys,
> 
> where is the .net core nuget package feed so I can download it?

@igatanasov this issue was only created 31 minutes ago.

**Comment by igatanasov** [comment]
Sorry guys, 

I missed this! Do you need any help with this issue?

**Comment by blairconrad** [comment]
@igatanasov, @jonorossi may feel differently (and it's his project, so I should keep my mouth shut), but it's probably best at least to see if something exciting happens with .NET core RC2 by the end of Build, and that will help suggest a direction for this issue.

**Comment by jonorossi** [comment]
Since nothing came out of BUILD and yesterday's ASP.NET Community Standup indicates pretty clearly RC2 is still a while away:

> During the Build conference, there was some rumbling about targeting April for RC2 and the team is hoping to hit that.  Damian isn’t quite ready to set a date yet, but is hopeful that it will be in April.
> (https://blogs.msdn.microsoft.com/webdev/2016/04/06/notes-from-the-asp-net-community-standup-april-5-2016/)

I've gone ahead and made a `4.0.0-alpha001` release:
* http://www.castleproject.org/blog/2016/04/07/core-4-0-0-alpha001-release/
* https://www.nuget.org/packages/Castle.Core/4.0.0-alpha001

Please log any problems you find with this version as separate issues, thanks.

**Comment by igatanasov** [comment]
Thanks @jonorossi

**Comment by blairconrad** [comment]
Indeed thanks, @jonorossi. I'm sorry I didn't come back to this issue to contribute work after Build, but the FakeItEasy 2.0 issue list got hot.
I'm sure some of us will enjoy playing with the alpha package on the side.
We appreciate your hard work.
