### ISSUE TITLE
Consider moving compatibility extensions into Castle.Core namespace

### ISSUE THREAD

**Issue by jeremymeng** [castleproject/Core#194]
Currently we have compatibility extension methods defined in `System.Reflection` namespaces for NET40.  This could cause conflicts when consumer have mixed framework versions.  It could have been avoided were these extension methods defined in Castle.Core's own namespaces.

For example, FakeItEasy library is targeting v4.0, thus it references v4.0 of Castle.Core, which defines `System.Reflection.IntrospectionExtensions.GetTypeInfo()` extension method.  However FakeItEasy.Tests targets v4.5 while referencing the v4.0 FakeItEasy project (this is valid).  FakeItEasy.Tests cannot disambiguate the extension method from Castle.Core and the one from the .NET Framework v4.5.

**Comment by jeremymeng** [comment]
Or would making it internal work?

Things to consider if we decide to move into private namespace

- What namespace? `Castle.Core`/`Castle.Core.Compatibility`/`Castle.Core.Internal`?
- One drawback: might need to conditionally using `System.Reflection` or the private namespace, otherwise one of them becomes unused.

**Comment by jeremymeng** [comment]
FakeItEasy is using ILMerge that's why FakeItEasy see this internal class.

**Comment by jonorossi** [comment]
@jeremymeng I'm not really interested in changing the namespace. I want them to emulate as close as possible, so having different `using x;` would be painful because it would cause compilation errors on old frameworks when we make changes making it more work to maintain old frameworks. The reflection differences between frameworks are painful enough to deal with.

What is the exact error message? Since these are extension methods (i.e. we don't explicitly use the class name) would renaming our static classes fix the resolution, or is it a compile time error and still just finds two ambiguous extension methods?

Out of curiosity why wasn't this found months ago?

**Comment by jeremymeng** [comment]
> so having different using x; would be painful because it would cause compilation errors on old frameworks when we make changes making it more work to maintain old frameworks.

Yes I agree. 



> or is it a compile time error and still just finds two ambiguous extension methods?

Yes, compile time error, because of the two extension methods are both in scope with `using System.Reflection`.  Renaming class wouldn't help.



> Out of curiosity why wasn't this found months ago?

I found it when porting FakeItEasy tests.  I worked around it by upgrading the FakeItEasy class lib project to v4.5.  However, FakeItEasy owners are wondering whether it's possible to avoid adding a v4.5 project.

**Comment by jeremymeng** [comment]
(Sorry I am not at the dev machine right now so cannot paste the exact error message.)

**Comment by jeremymeng** [comment]
compile errors like
```
2>C:\github\jeremymeng\FakeItEasy\tests\FakeItEasy.Tests\NullGuardedAssertion.cs(158,34,158,45): error CS0121: The call is ambiguous between the following methods or properties: 'System.Reflection.IntrospectionExtensions.GetTypeInfo(System.Type)' and 'System.Reflection.IntrospectionExtensions.GetTypeInfo(System.Type)'
```

**Comment by jonorossi** [comment]
Okay, that means that FakeItEasy.Tests are being compiled against the ILMerged FakeItEasy.dll rather than the pre-ILMerging ...yep [ILMerging is done as a post-build step in the csproj file](https://github.com/FakeItEasy/FakeItEasy/blob/275d3097d465f7afa22dad18995db0af5ab5e488/src/FakeItEasy/FakeItEasy.csproj#L483-L485), which also would slow down development since it is done after every compile. Surprised it isn't just done in their build script before running the unit tests.

If ILMerging was done in the rakefile before running the unit tests it could be done for both .NET Framework and .NET Core, and this problem wouldn't surface because the unit test project would be compiled against the actual public API contract that Castle Core ships.

I suspect the above change would be more doable than downgrading FakeItEasy.Tests to target .NET 4.0.

/cc @blairconrad @adamralph

**Comment by blairconrad** [comment]
Hi, @jonorossi. Thanks for chiming in.

> If ILMerging was done in the rakefile before running the unit tests it could be done for both .NET Framework and .NET Core, and this problem wouldn't surface because the unit test project would be compiled against the actual public API contract that Castle Core ships.

It would introduce the slight inconsistency that running the tests in the IDE (for example) would operate against the non-ILMerged version of the FakeItEasy DLL (if I'm understanding you properly).
I doubt it would cause any problems and the CI server would eventually run the tests against the merged DLL, so this is probably okay, but thought I'd bring it up in case anyone else had a concern.

However, I'm very interested in this, since up 'til now we thought ILMerging wasn't available for .NET Core.

> I suspect the above change would be more doable than downgrading FakeItEasy.Tests to target .NET 4.0.

Yeah, we use XUnit 2.0, which doesn't have a .NET 4.0 flavour.
/cc @thomaslevesque, @adamralph

**Comment by jonorossi** [comment]
> However, I'm very interested in this, since up 'til now we thought ILMerging wasn't available for .NET Core.

FYI, I haven't tried ILMerge with .NET Core assemblies, so unless there is some crazy stuff going on like the old Silverlight days then I can't think of any reason it wouldn't work, unless PCLs or other System.Runtime based assemblies don't work with it.

> Yeah, we use XUnit 2.0, which doesn't have a .NET 4.0 flavour.

Ah. In time we'll drop support for .NET 4.0 in Castle Core too since it hasn't been supported by Microsoft for quite a while now, we'll keep .NET 3.5 while it is still supported though. No plans yet though, we'll probably wait until .NET 3.5 is no longer supported.

**Comment by adamralph** [comment]
> ILMerging is done as a post-build step in the csproj file, which also would slow down development since it is done after every compile

Barely noticeable.

**Comment by blairconrad** [comment]
Sure, @adamralph. I've nearly no interest in getting these milliseconds back. But if it means we can ILMerge in the .NET Core case…

**Comment by blairconrad** [comment]
…although I don't understand why ILMerging will work from the command line but not from within the .NET Core in-IDE compile.

**Comment by adamralph** [comment]
Indeed, the post build step is just invoking the exe, so can't see what difference putting it in the build script would make.

**Comment by jeremymeng** [comment]
I had spent some time trying ILMerge on .NET Core when porting Moq.  There are some issues I hit.

- The .NET Framework reference assemblies are not under `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v5.0\`.  They are in NuGet packages.  ILMerge seems to need this.
- Running ILMerge on .NET Core PCL assemblies leads to crash due to InvalidCastException.  Mike Barnett, the author of ILMerge suspected that it can't be fixed.

**Comment by adamralph** [comment]
@jeremymeng did you try [ILRepack](https://github.com/gluck/il-repack)?

**Comment by jeremymeng** [comment]
> @jeremymeng did you try ILRepack?

I have not.  in Moq we just changed to take dependency on Castle.Core from NuGet.

I did a little bit exploration and seemed to hit a dead end.

I need to specify a directory for `/lib:` to find the assemblies.  However, the project.json based PCL project doesn't copy dependencies to the output directory.  It seems that setting `CopyNuGetImplementations` to `true` should do it, but then it doesn't work with class library project.  It requires specifying runtimes, which isn't right for a portable class lib.  Anyway adding runtimes section caused more restoring errors.  I didn't go further.

**Comment by jonorossi** [comment]
As I've mentioned I would really only want to make this change if there wasn't a workaround on your end because of how heavily we use reflection. Supporting Silverlight's differences was extremely painful, so this would only push us to want to drop .NET 3.5 and 4.0 quicker.

I proposed compiling the unit tests against the non-merged assembly, however it looks like you've gone down another route using aliases which looks fine so I'm closing this issue as it is no longer needed. Thanks.

**Comment by thomaslevesque** [comment]
@jonorossi no problem, we should be able to work around the issue.

**Comment by blairconrad** [comment]
Thanks for entertaining the idea, and your continued help, @jonorossi.
