### ISSUE TITLE
Can a Castle Dynamic generated proxy be forced to implement members as explicit interface implementations?

### ISSUE THREAD

**Issue by mfidemraizer** [castleproject/Core#213]
Hi!

I've a very simple question which I don't know if it has an easy answer, but let's see.

For example, let's say I've defined an interface as follows:

    public interface IWhatever
    {
         string Text { get; set; }
    }

And I implement it in a mixin:

    public class WhateverMixin : IWhatever
    {
         string IWhatever.Text { get; set; }
    }

When I build a proxy of something given class, the whole explicitly-implemented interface member appears as implicitly implemented so it gets *published*.

Do you know if there's some options I can give to Castle DynamicProxy to force implementing an interface with explicit implementations?

I've also published this question on [StackOverflow](http://stackoverflow.com/questions/38593185/can-a-castle-dynamic-generated-proxy-be-forced-to-implement-members-as-explicit).

**Comment by jonorossi** [comment]
@mfidemraizer As answered on StackOverflow, DynamicProxy does not currently provide this ability. We do have other support for explicitly implemented members, but obviously not with mixins.

Closing as this issue is written as a question, not a feature request.

**Comment by mfidemraizer** [comment]
@jonorossi And two simple questions:

a) It would be very hard to implement this feature on mixins? I could contribute it, but if it would require an big refactor, I wouldn't do it because it could introduce breaking changes...

b) What's the other support for explicitly implemented members during proxy generation?

Thank you in advance

**Comment by jonorossi** [comment]
@mfidemraizer to be honest I'm not sure, but I don't think it would require a big refactor.

We currently handle explicitly implemented interfaces on class proxies and interface proxies with a target, mixins aren't that commonly used. See [ExplicitInterfaceTestCase.cs]( https://github.com/castleproject/Core/blob/5ddeb0df48615d725531a506c61905188e0d0d70/src/Castle.Core.Tests/DynamicProxy.Tests/ExplicitInterfaceTestCase.cs) for some of the explicit implementation unit tests, and take a look at [MetaMethod.SwitchToExplicitImplementation](https://github.com/castleproject/Core/blob/2acd42b27e3fae643f203d9a3ee1cfdb3a7e7bfd/src/Castle.Core/DynamicProxy/Generators/MetaMethod.cs#L96-L105).

I do recall there have been problems in the past with explicitly implemented interfaces because these methods are marked final/sealed even though they are virtual so some scenarios are just not valid.

P.S. feel free to reopen this issue, but change the title.

**Comment by mfidemraizer** [comment]
@jonorossi Thanks for the info.

I'll take a look at the test cases and see if it can solve my issue in my project. If not, I'll consider checking how would I provide the whole feature on DynamicProxy and I'll see if I'm able to implement it because I'll have to study hard the code :)

Well, thank you again!
