### ISSUE TITLE
Change usages of __MonoCS__ to the NUnit PlatformAttribute

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#227]
We currently use the `__MonoCS__` compiler define in unit tests to alter the behaviour of unit tests when run on the Mono runtime, however this define was only meant to indicate the Mono compiler was being used.

With Mono moving to the Roslyn compiler this define will no longer be defined:
https://lists.dot.net/pipermail/mono-devel-list/2017-January/044104.html

We should probably move the remaining uses of this define to that `[Platform]` attribute.

**Comment by fir3pho3nixx** [comment]
After https://github.com/castleproject/Core/issues/241 I would be happy to check this out.

**Comment by fir3pho3nixx** [comment]
@jonorossi - is this still relevant?

**Comment by jonorossi** [comment]
We have worked around this as we've changed to the new .NET tooling to use Mono on Linux by defining this ourselves in common.props, however we should still migrate to using `PlatformAttribute` like some of our unit tests already do, however I didn't want to just do it as a bulk find/replace because you really do want to put a reason in the attribute's constructor so you know why it can't work on Mono (some might already be fixed on a newer version of Mono).

```
<DesktopClrConstants Condition="'$(OS)'=='Unix'">$(CommonDesktopClrConstants);__MonoCS__</DesktopClrConstants>
```
(https://github.com/castleproject/Core/blob/v4.1.0/buildscripts/common.props#L42)

**Comment by stakx** [comment]
> We should probably move the remaining uses of [the `__MonoCS__` conditional compilation symbol] to that `[Platform]` attribute.

@jonorossi - I've just noticed that this is probably not going to work out: Tests marked with the `[Platform]` attribute won't compile on .NET Core because that attribute is not available in NUnit's .NET Standard version (which that's the one that gets used when compiling for .NET Core).

The reason why this wasn't a problem so far was because all tests carrying a `[Platform]` attribute were already skipped by conditional compilation symbols that aren't defined for .NET Core (`FEATURE_ASSEMBLYBUILDER`, `FEATURE_CONFIGURATION`, `FEATURE_SECURITY_PERMISSIONS`).

**Comment by jonorossi** [comment]
@stakx great work. Your pull request will definitely help when we add a .NET Standard 2.0 build in the future and start adding some features back in.
