### ISSUE TITLE
Replace adodb.dll used in unit tests with dynamically generated type

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#280]
We currently have some random `adodb.dll` committed to our source repository used by `ComInterfacesTests`, can we get rid of it the same way we got rid of `Rhino.Mocks.CPP.Interfaces.dll` in #277?

/cc @stakx

**Comment by stakx** [comment]
I saw that DLL, but wasn't sure where it belonged to, so I opted not to touch it. I can look into it later today, if you'd like.

**Comment by jonorossi** [comment]
@stakx that would be great.

**Comment by stakx** [comment]
### What is `adodb.dll`? ###

`adodb.dll` turns out to be an older version of the ActiveX Data Objects (ADO) Primary Interop Assembly. That is, it contains COM interop type definitions describing COM components that need to be installed on your system for your unit tests to run successfully. For example, on my box, the unit tests in `ComInterfaceTypes.cs` (which reference `adodb.dll`) will cause COM components in `C:\Program Files\Common Files\System\ado\msado15.dll` to be loaded at runtime. Fortunately, from what I can tell, those ADO components are probably always installed on a VS developer box.

### How can we get rid of it, and what do we gain by it? ###

We can get rid of `adodb.dll` quite easily, namely by reproducing the COM interop type declarations it contains as C# interfaces (decorated with `[ComImport]`, `[Guid]`, and the like) in the unit test project. However, getting rid of `adodb.dll` does not remove the runtime dependency on the COM components those declarations describe!

### Can we get rid of the runtime dependency, too? ###

If we want Castle.Core unit tests to be fully self-contained, i.e. have no dependencies on any pre-installed  external COM DLLs, we would need to implement our own COM or COM-like component. I can do this and send a PR, but before I do so, I'd like you to know what this implies:

 * We should not implement our own COM component as managed code, but using unmanaged C or C++. A single small, [lightweight COM](https://stackoverflow.com/questions/38174095/what-exactly-is-lightweight-com) component would do. We don't even need to register the resulting DLL with the operating system's COM subsystem (which only exists on Windows, anyway). All we'd rely on is .NET's P/Invoke and COM interop facilities.

 * But we still have C or C++ code which we need to be able to compile. We'll need to make sure the CI servers have MSVC and are configured to compile a VS C++ project. I expect this to be the main difficulty.

 * As we're compiling to native code, we'll end up with two DLLs: one for x64 and one for x86, to support all boxes where Castle's unit tests might run. (If we know that the unit tests will run only on e.g. x64 machines, we can omit the x86 DLL.)

* Finally, we add the necessary P/Invoke and COM interop definitions in Castle.Core's unit test project that match the stuff in our C++ DLL. Again, that's fairly straightforward. Again, this is quite straightforward.

This probably sounds like more work than it really is, I just wanted to make sure you know the consequences of getting rid of `adodb.dll`.

### Recommendation: ###

We can start by extracting the required COM interop type declarations from `adodb.dll` and reproducing them in the unit test project as C# type declarations. Then we can drop `adodb.dll`.

Once that's done, you could still decide if you want to go further and remove the external runtime dependency.

Let me know if you'd like to go ahead with this (and how far you want to go), and I'll prepare a PR. Shouldn't take too long.

**Comment by fir3pho3nixx** [comment]
@stakx - Your approach here is definitely heading in the right direction. ADODB does not appear to be a valid dependency. @jonorossi and I have had subjective discussions around whether COM is dead or not. Turns out it features heavily in WRL, the successor of ATL. So we should perhaps nurture the interface to COM but keep it on the CLR side as you say.

**Comment by jonorossi** [comment]
@stakx many thanks for the detailed response.

> What is adodb.dll?

Yep, ADODB is part of MDAC that ships with Windows, not sure if they ship it on Server Core by default. My comment about random was more than we've picked up this primary interop assembly that was created from VS2012/.NET 1.0 tooling.

> However, getting rid of adodb.dll does not remove the runtime dependency on the COM implementation DLLs!

I didn't think the unit test needed the implementation, but I somehow forgot to read the code, it'll call `CoCreateInstance` twice which is good otherwise I'd be a pretty poor unit test, and I forgot that DynamicProxy itself actually calls `QueryInterface` which needs the implementation registered. Thanks.

I'm unsure why you think we shouldn't implement a COM component using managed code, you can export a COM interface from C# and use the exported type library, I've developed software that was a mix of C++ and C# during transition and there was COM going in both directions like this.

With that said, I'd prefer to keep this simple. Since we already require the Windows SDK to run `peverify` why not use `tlbimp` and generate the interop assembly if it doesn't exist (i.e. use an MSBuild conditional that only runs tlbimp if the file doesn't exist). I have tested it, the native DLL does have its type library stored as a embedded resource so tlbimp works.

```
tlbimp "C:\Program Files\Common Files\System\ado\msado15.dll"
```

Thoughts?

**Comment by jonorossi** [comment]
> I have had subjective discussions around whether COM is dead or not. Turns out it features heavily in WRL, the successor of ATL. So we should perhaps nurture the interface to COM but keep it on the CLR side as you say.

@fir3pho3nixx Well the implementation is using COM, however you can't use DynamicProxy in Windows Store apps yet (emitting code not allowed), no idea if you could use it with the Windows Runtime though, however there really is no use case for people to use it without targeting the store AFAIK. I'm sure there are still heaps of people using COM on .NET Framework though, especially to try mocking those interfaces even a little.

**Comment by stakx** [comment]
>I'm unsure why you think we shouldn't implement a COM component using managed code,  […]

If you implement a COM component in C#, you cannot do "lightweight" COM. AFAIK, you will be required to register the component with the COM subsystem (`regasm`) in order to be able to instantiate and use it. I was assuming (perhaps too soon) that registration might be a problem, since it requires admin privileges, and those might not be a given on the CI servers.

I was also considering whether COM-based unit tests would be a tad "unrealistic" if they dealt with a RCW around a CCW around managed code... the CLR might possibly take some shortcuts and act differently than when given a fully unmanaged coclass.

But of course you're right, implementing a COM component in .NET would be perfectly feasible apart from those considerations.

> why not use tlbimp and generate the interop assembly if it doesn't exist

It's definitely possible to generate `adodb.dll` that way. But why get rid of `adodb.dll` only to attempt generating it during a build? What would be gained, except perhaps that DLL being more up-to-date?

**Comment by jonorossi** [comment]
> If you implement a COM component in C#, you cannot do "lightweight" COM

Ah, yer I've not used lightweight COM that is a newer feature, always had to stuff around with painfully registering classes. We definitely don't want to have to register classes in unit tests.

> It's definitely possible to generate adodb.dll that way. But why get rid of adodb.dll only to attempt generating it during a build? What would be gained, except perhaps that DLL being more up-to-date?

I guess I dislike binaries. To me at least, it appears the best/simplest option would be to continue with adodb.dll committed until we actually have a problem with using it.

**Comment by stakx** [comment]
@jonorossi, I agree.

That being said, the unit tests in `ComInterfaceTests.cs` could need some more attention.. When I initially looked at them, I didn't really understand what they were supposed to test (and I'm still not entirely sure I do now :-). The fact that I found two potential bugs related to COM interfaces in `ProxyGenerator` suggests that those tests could be more thorough.

But perhaps that, too, can wait until someone actually has a problem with it. I'm happy to look at this again and come up with something, though, if you'd prefer to get this fixed while we're still looking at it.

**Comment by jonorossi** [comment]
I agree, the unit test isn't clear at all what it was testing.

If you've got the time to clean them up and look into the other error condition bug then go for it. I assume a user though will get some other exception pretty quickly if you get E_NOINTERFACE from QueryInterface so it might not have ever popped up, or no one reported the error.

**Comment by jonorossi** [comment]
Closing this issue since we'll leave adodb.dll as is.
