### ISSUE TITLE
ProxyUtil.IsAccessible(MethodBase) reports false positive for method declared in internal class

### ISSUE THREAD

**Issue by stakx** [castleproject/Core#289]
I just noticed that in Castle.Core 4.1.1, [`Castle.DynamicProxy.ProxyUtil.IsAccessible(MethodBase method)`](https://github.com/castleproject/Core/blob/1e2b33249e2e23448f68a6ef5674b8eb532d1dae/src/Castle.Core/DynamicProxy/ProxyUtil.cs#L86-L93) appears to report false positives for methods declared within internal classes:

```csharp
using Castle.DynamicProxy;

// [assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")] has not been declared.

public abstract class P
{
    internal abstract void I();
}

internal abstract class I
{
    public abstract void P();
}

public class ProxyUtilTestCase
{
    [Test]
    public void IsAccessible_GivenInternalMethodInPublicClass_ReturnsFalse()
    {
        var pi = typeof(P).GetMethod("I", BindingFlags.NonPublic | BindingFlags.Instance);
        Assert.False(ProxyUtil.IsAccessible(pi));  // passes
    }

    [Test]
    public void IsAccessible_GivenPublicMethodInInternalClass_ReturnsFalse()
    {
        var ip = typeof(I).GetMethod("P", BindingFlags.Public | BindingFlags.Instance);
        Assert.False(ProxyUtil.IsAccessible(ip));  // fails
    }
}
```

How can method `I.P` be accessible to DynamicProxy when the declaring type `I` isn't? After all, `new ProxyGenerator().CreateClassProxy<I>()` would fail.

Am I misunderstanding the purpose of that method, or can you confirm that this is a bug?

**Comment by jonorossi** [comment]
Yep, it's a bug. As you might already be aware `Castle.DynamicProxy.ProxyUtil.IsAccessible(MethodBase)` was added in 4.1.0, but it just delegates to `Castle.DynamicProxy.Internal.InternalsUtil.IsAccessible(this MethodBase)` which has been there forever. The whole point it was added was so consumers of DynamicProxy could provide useful error messages when attempting to proxy something unproxyable but get these messages added to their own exception rather than wait for DynamicProxy to throw one. @blairconrad requested it for FakeItEasy.

You can [see in `InternalsUtils` that it doesn't check the type's accessibility at all](https://github.com/castleproject/Core/blob/v4.1.1/src/Castle.Core/DynamicProxy/Internal/InternalsUtil.cs#L77-L100), the 4 places this utility method is used in DynamicProxy it doesn't need to because it was already checked before that code was coded for each method:

We'll need to bring [this code from `DefaultProxyBuilder`](https://github.com/castleproject/Core/blob/v4.1.1/src/Castle.Core/DynamicProxy/DefaultProxyBuilder.cs#L148-L165) and probably add a `IsAccessible(Type)` overload, then the method overload can call the type overload. Probably best to leave `InternalsUtil` as is to keep performance the same, and bolster `ProxyUtil`.

/cc @blairconrad

**Comment by stakx** [comment]
Thanks for the quick response, @jonorossi!

> The whole point it was added was so consumers of DynamicProxy could provide useful error messages when attempting to proxy something unproxyable.

That's the use case I'm looking at for Moq. (Thanks @blairconrad for paving the way!)

You're suggesting to extend `ProxyUtil.IsAccessible` but keep `InternalsUtil.IsAccessible` as is. I see the reasoning behind it, but this could potentially confuse users, since from their viewpoint both methods are accessible and look pretty much identical. Perhaps it would be good to bring back [this point raised by @blairconrad](https://github.com/castleproject/Core/issues/235#issuecomment-284929772):

> `Castle.DynamicProxy.Internal.InternalsUtil.IsAccessible` exists, and is public (in fact, FakeItEasy uses it). If anything's a candidate for deprecation, it's this.

A possible first step in phasing `InternalsUtil.IsAccessible` out of the public API might be to hide it from public view via `[EditorBrowsable(EditorBrowsableState.Never)]` to prevent new uses. (Ideally, it would also be marked `[Obsolete]` to warn people about existing uses, but that might be a no-go since you're actually using it internally.) Then, in a later version, it could be redeclared `internal`.

> and probably add a `IsAccessible(Type)` overload

That would be a welcome addition. 👍

**Comment by jonorossi** [comment]
> A possible first step in phasing InternalsUtil.IsAccessible out of the public API might be to hide it from public view via [EditorBrowsable(EditorBrowsableState.Never)] to prevent new uses. (Ideally, it would also be marked [Obsolete] to warn people about existing uses, but that might be a no-go since you're actually using it internally.) Then, in a later version, it could be redeclared internal.

I'd merge a pull request that added `[EditorBrowsable(EditorBrowsableState.Never)]` to all `InternalsUtil` members, however I think we can do one better.

As you said we can't just mark them `[Obsolete]` since we use them, however we could create a new util class in another namespace which the DP code can use, and this one in the `Castle.DynamicProxy.Internal` namespace can call into the new one. Maybe that new util class can be `ProxyUtil`, we could add an internal method named `IsAccessibleMethod` that only checks the method, which the public `IsAccessible` can call. We should pull the code out of `DefaultProxyBuilder` into `ProxyUtil` too to centralise what we classify as "accessible".

**Comment by stakx** [comment]
I hope that PR is more or less what you had in mind. Otherwise just let me know.

On a different note, I came across [this line of code](https://github.com/stakx/Core/blob/e1ce0f8037aa77c42be1285ed4ccf5a1ed81a817/src/Castle.Core/DynamicProxy/ProxyUtil.cs#L275):

> `"Can not create proxy for method {0} because it or its declaring type is not accessible."`

and couldn't help thinking that this is somewhat incorrect: DynamicProxy creates proxies for types, not for methods (AFAIK). (Perhaps @blairconrad could suggest a different wording that also plays well with FakeItEasy?)

**Comment by blairconrad** [comment]
@stakx, good catch, and it's good of you to think of us. We wrap the returned string so the phrasing can vary however Castle.Core likes. This is the kind of thing a FakeItEasy user would see if they tried to configure an inaccessible method:

```
The current proxy generator can not intercept the method FakeItEasy.Specs.TypeWithInternalMethod.InternalMethod() for the following reason:
   - Can not create proxy for method Int32 InternalMethod() because it is not accessible. Make it public, or internal and mark your assembly with [assembly: InternalsVisibleTo(""DynamicProxyGenAssembly2"")] attribute, because assembly FakeItEasy.Specs is not strong-named.
```

Reading this, I think "Can not intercept method …" would have worked for the Castle.Core message as well. It will make FakeItEasy's message redundant, but that's fine.

**Comment by jonorossi** [comment]
Thanks @stakx, I've done a code review on the pull request.

**Comment by stakx** [comment]
Thanks for the review. I made the requested changes. And even managed to remember the changelog. :-)

**Comment by jonorossi** [comment]
All merged, thanks.
