### ISSUE TITLE
Duplicate invocation of EnsureValidTarget method

### ISSUE THREAD

**Issue by yallie** [castleproject/Core#295]
I've inspected the generated invocation class using Reflector and found 
that `EnsureValidTarget` method is invoked twice:

```c#
public override void InvokeMethodOnTarget()
{
      base.EnsureValidTarget(); // #1
      base.EnsureValidTarget(); // #2
      string str = (base.target as IEventHandler).Handle((EventArgs) base.GetArgumentValue(0));
      base.ReturnValue = str;
}
```

These method calls are generated here:
* [InvocationTypeGenerator, line 120](https://github.com/castleproject/Core/blob/master/src/Castle.Core/DynamicProxy/Generators/InvocationTypeGenerator.cs#L120-L123) — for proxies that can change target
* [CompositionInvocationTypeGenerator, line 63](https://github.com/castleproject/Core/blob/master/src/Castle.Core/DynamicProxy/Generators/CompositionInvocationTypeGenerator.cs#L63-L65) — for all proxies

It's not really a big deal, but it seems quite easy to avoid.
Perhaps by having a flag, something like `ensureValidTargetEmitted`.

**Comment by jonorossi** [comment]
Not sure if we even need it in `CompositionInvocationTypeGenerator`, however it is hard to tell from the control flow because of quite a number of conditions and generator subclasses.

If we can't work out if the first one is needed, I'd guess the cleanest fix would be to change `InvocationTypeGenerator.EmitCallEnsureValidTarget` to protected to remove the duplication and only write it once with a flag, which I think is what you were probably suggesting.

**Comment by stakx** [comment]
A small aside, I have privately worked on this a bit (https://github.com/stakx/Castle.Core/commit/1e25a6f6dd109589f087715cb4809090304489d7). I also couldn't figure out whether the enforced call in `CompositionInvocationTypeGenerator` is needed, so I opted to follow the above suggestion and introduce a flag to ensure once-only call emission.

I'm happy to submit a proper PR for this, but if anyone has a better solution then that should go first. I guess we're not in a hurry here since this is a fairly minor bug.

**Comment by stakx** [comment]
> Not sure if we even need it in `CompositionInvocationTypeGenerator`, however it is hard to tell from the control flow because of quite a number of conditions and generator subclasses.

After looking at this issue again, the solution has become clear to me. It turns out to be simpler than assumed. Let's take a look at the types involved. Can you spot the problem?

![ensurevalidtarget](https://user-images.githubusercontent.com/104481/41818793-e335d784-77b5-11e8-922e-50ebf75c9800.png)


The problem is that only one of the two invocation types (`CompositionInvocation`) has an `EnsureValidTarget` method, yet it is not the specialized generator class corresponding to it that emits the call, but the base generator class!

https://github.com/castleproject/Core/blob/da8153f068600a15796461122df8402400701196/src/Castle.Core/DynamicProxy/Generators/InvocationTypeGenerator.cs#L120-L123

You'll notice that the call is only emitted if `canChangeTarget == true`. This is a readonly field that gets set by the constructor.

Here is how `CompositionTypeGenerator` calls into that constructor:

https://github.com/castleproject/Core/blob/da8153f068600a15796461122df8402400701196/src/Castle.Core/DynamicProxy/Generators/CompositionInvocationTypeGenerator.cs#L29-L33

And for `InheritanceInvocationTypeGenerator`:


https://github.com/castleproject/Core/blob/da8153f068600a15796461122df8402400701196/src/Castle.Core/DynamicProxy/Generators/InheritanceInvocationTypeGenerator.cs#L28-L32

Note the `false`, this is the value that'll get stored in `canChangeTarget`.

So, the conclusion is that `InheritanceInvocationTypeGenerator` will *never* emit a call to `EnsureValidTarget` (as it should be, since that method doesn't exist on `InheritanceInvocation`). We can therefore safely move the `EmitCallEnsureValidTarget` into `CompositionInvocationTypeGenerator`.

**Comment by jonorossi** [comment]
Good catch:

```csharp
public static class InvocationMethods
{
    public static readonly MethodInfo EnsureValidTarget =
        typeof(CompositionInvocation).GetMethod("EnsureValidTarget", BindingFlags.Instance | BindingFlags.NonPublic);
}
```

With that now known, we should rename `InvocationMethods.EnsureValidTarget` to `CompositionInvocationEnsureValidTarget` to match all the other ones (all but 2 that aren't in `AbstractInvocation` are prefixed). We should probably also fix `InvocationMethods.Target` since that is from `CompositionInvocation` too.

> The only question remaining is whether the emit in `CompositionInvocationTypeGenerator` should be in fact conditional (i.e. only when `canChangeTarget == true`), or unconditional (as is now).

I haven't dug into it but composition based proxies obviously may not have a target, but this check for a valid target is being emitted inside the invocation's `InvokeMethodOnTarget` method so it is obviously expecting a target or it will end up throwing. My guess is the condition using `canChangeTarget` was actually semantically wrong and it just happened to work because you can't change an inheritance proxy's target, while for composition based proxies as long as you have a target you can change it, so this condition was basically determining the type of proxy. So, no I don't think the `CompositionInvocationTypeGenerator` needs the condition.

**Comment by stakx** [comment]
@jonorossi - I've included both renames in the PR.

I noticed briefly that there appears to be a similar "design" issue in `InvocationTypeGenerator` concerning the logic that implements the `IChangeProxyTarget` interface. This should possibly be moved into `CompositionInvocationTypeGenerator`, too. However, it's not directly related to this issue, so I'd say let's look at that in a separate PR.
