### ISSUE TITLE
Does not compile without FEATURE_SECURITY_PERMISSIONS

### ISSUE THREAD

**Issue by s-bauer** [castleproject/Core#304]
Hey, I just noticed that Castle.Core doesn't compile when the `FEATURE_SECURITY_PERMISSIONS` is not set. There's an error in the File  `DefaultSmtpSender` in the function `CanAccessCredentials`. Can someone check that please? Thanks

**Comment by jonorossi** [comment]
@s-bauer what are you attempting to do? We don't really support being able to pick and choose what symbols you want to define, they are really there for us to support .NET Standard.

**Comment by fir3pho3nixx** [comment]
@s-bauer - I agree whole heartedly with @jonorossi. These build symbols were very carefully crafted to support netstandard, the same thing is happening down in Castle Windsor. You really should not be optionally dropping symbols of your choosing out because they simply were not coded/tested that way. It is not the reason they are there.

If it is for learning purposes we are happy to guide you and continue the conversation. Ideally you would create a new issue with a proper description of what you are trying to achieve and we can have a better focused chat.

I am closing this for now. We can continue the discussion though. Hope you understand.
