### ISSUE TITLE
Integrate with Common Logging

### ISSUE THREAD

**Issue by davidshen84** [castleproject/Core#321]
[Common Logging][1] looks like a sane project. Would people like the idea that Castle integrate this logging interface. This should remove the necessity to implement and maintain a range of logging frameworks by Castle project.

Both Castle and Common Logging are using Apache 2.0 license.

[1]: http://net-commons.github.io/common-logging/

**Comment by fir3pho3nixx** [comment]
Not convinced. If anything I want reduce vendor lock-in when it comes to logging libraries or abstractions. These things are so trivial to implement if done right, why oh why do we need another layer of abstraction around this? What if a user only wants feature X from log4net but Common Logging does not implement feature X because it is different from the SeriLog driver? This is really stuff that should be in the users directly.

**Comment by jonorossi** [comment]
I agree with @fir3pho3nixx, Common.Logging is quite a complicated project and if we wanted to keep an abstraction I'd prefer to just keep the one we've got rather than move to yet another as it doesn't simplify build/test time dependencies.

Check out https://github.com/castleproject/Windsor/issues/339 where we are currently talking on this topic. I'll close this in favour of the discussion in the Windsor repo.
