### ISSUE TITLE
Memory leak in the ProxyGenerator

### ISSUE THREAD

**Issue by metatem** [castleproject/Core#329]
We found what seems to be a memory leak in the ProxyGenerator when it is created and CreateInterfaceProxyWithoutTarget is called on the newly created object.

We have prepared a sample project which shows the problem,
You can enable/disable the demonstration with the `showMemoryLeak` flag in the beginning in the sample project.

If enabled a new instance of the ProxyGenerator is created each time and the memory consumption is growing. And if it is disabled the sample is using a single instance of a ProxyGenerator in which case the memory stays fine. We are using the latest available version of the package - v4.2.1

Here is the sample project: [SampleMemoryLeakCastleCore.zip](https://github.com/castleproject/Core/files/1539568/SampleMemoryLeakCastleCore.zip)

**Comment by jonorossi** [comment]
> If enabled a new instance of the ProxyGenerator is created each time and the memory consumption is growing. And if it is disabled the sample is using a single instance of a ProxyGenerator in which case the memory stays fine.

I haven't looked at the same project but this is the expected behaviour, see the warning on the [home page of the DynamicProxy docs](https://github.com/castleproject/Core/blob/master/docs/dynamicproxy.md). Each `ProxyGenerator` will use its own dynamic assembly, these assemblies are not unloaded and we do not make use of `AssemblyBuilderAccess.RunAndCollect`. For performance reasons you should reuse the same `ProxyGenerator` wherever possible because type generation does take a non trivial amount of time.

If this doesn't answer you question please reopen.

**Comment by metatem** [comment]
I understand now. Thanks a lot for the explanation.
I apologize for not seeing the warning earlier. We'll use a single instance as is recommended.
Thanks
