### ISSUE TITLE
Cross-platform/ .NETStandard support

### ISSUE THREAD

**Issue by godrose** [castleproject/Core#333]
Is there any roadmap of having this great functionality ported to any version of .NETStandard?
Is this even possible, either partially or fully, given the limitations of `Reflection` there?

**Comment by jonorossi** [comment]
I'm not sure exactly what you are referring to but most of Castle Core has been available for .NET Standard 1.3 since v4.0.0, the first pre-release was published in April 2016.

Some minor features are still conditionally compiled out, you can see compilation symbols and brief descriptions in the readme: https://github.com/castleproject/Core#conditional-compilation-symbols

**Comment by jonorossi** [comment]
And we've supported Mono for quite some time, see supported version info also in the readme: https://github.com/castleproject/Core#mono
