### ISSUE TITLE
What to do about the Castle Scheduler documentation?

### ISSUE THREAD

**Issue by stakx** [castleproject/Core#368]
I just noticed something in Core's documentation called "Castle Scheduler"&mdash;a component that I've never come across in the source code. The types mentioned in [docs/scheduler.md](https://github.com/castleproject/Core/blob/38acf786cc72e8b851296e9fc4bb802e49e4e287/docs/scheduler.md) (`IScheduler`, `IJob`, `Trigger`, etc.) don't appear to exist in Core, nor in Windsor. The only place where some (but not all) of them show up is in Castle.Facilities.Quartz, but many of these types are actually defined by Quartz.

I suspect that the documentation on Castle Scheduler might be obsolete and should perhaps be removed. If not, should it be updated so it becomes clearer what exactly it's referring to?

**Comment by jonorossi** [comment]
The Scheduler component (aka `Castle.Components.Scheduler`) was deprecated a really long time ago and lives at https://github.com/castleproject-deprecated/Attic/tree/master/Scheduler.

I think that documentation ended up there because when I manually imported all the docs from our old wiki we had a ScrewTurn namespace for "Services and Tools" or something, and most of those ended up in Castle Core, e.g. logging services, DP tool, DA tool.

I've moved the obsolete docs (39457da1bd1cd835bfca4df8946fb9dcbe996c5e, https://github.com/castleproject-deprecated/Attic/commit/b69dd95dfb2f19c077fec8feb4ec99e680a6c7aa).
