### ISSUE TITLE
Change name of generated dynamic proxy type?

### ISSUE THREAD

**Issue by RudeySH** [castleproject/Core#380]
I want to change the name of the generated proxy type. I tried this:

https://stackoverflow.com/questions/4205637/castle-dynamicproxy-generated-class-names

But this doesn't seem to work with the latest version of Castle.Core. It doesn't matter how I implement my custom `INamingScope`, I always get the following exception:

```
System.ArgumentException: Duplicate type name within an assembly.
   at System.Reflection.Emit.ModuleBuilder.CheckTypeNameConflict(String strTypeName, Type enclosingType)
   at System.Reflection.Emit.AssemblyBuilderData.CheckTypeNameConflict(String strTypeName, TypeBuilder enclosingType)
   at System.Reflection.Emit.TypeBuilder.Init(String fullname, TypeAttributes attr, Type parent, Type[] interfaces, ModuleBuilder module, PackingSize iPackingSize, Int32 iTypeSize, TypeBuilder enclosingType)
   at System.Reflection.Emit.ModuleBuilder.DefineType(String name, TypeAttributes attr)
   at Castle.DynamicProxy.Generators.Emitters.ClassEmitter..ctor(ModuleScope modulescope, String name, Type baseType, IEnumerable`1 interfaces, TypeAttributes flags, Boolean forceUnsigned)
   at Castle.DynamicProxy.Generators.InvocationTypeGenerator.GetEmitter(ClassEmitter class, Type[] interfaces, INamingScope namingScope, MethodInfo methodInfo)
   at Castle.DynamicProxy.Generators.InvocationTypeGenerator.Generate(ClassEmitter class, ProxyGenerationOptions options, INamingScope namingScope)
   at Castle.DynamicProxy.Contributors.ClassProxyTargetContributor.BuildInvocationType(MetaMethod method, ClassEmitter class, ProxyGenerationOptions options)
   at Castle.DynamicProxy.Contributors.ClassProxyTargetContributor.GetMethodGenerator(MetaMethod method, ClassEmitter class, ProxyGenerationOptions options, OverrideMethodDelegate overrideMethod)
   at Castle.DynamicProxy.Contributors.CompositeTypeContributor.ImplementMethod(MetaMethod method, ClassEmitter class, ProxyGenerationOptions options, OverrideMethodDelegate overrideMethod)
   at Castle.DynamicProxy.Contributors.CompositeTypeContributor.Generate(ClassEmitter class, ProxyGenerationOptions options)
   at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateType(String name, Type[] interfaces, INamingScope namingScope)
   at Castle.DynamicProxy.Generators.ClassProxyGenerator.<>c__DisplayClass1_0.<GenerateCode>b__0(String n, INamingScope s)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
   at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateCode(Type[] interfaces, ProxyGenerationOptions options)
   at Castle.DynamicProxy.DefaultProxyBuilder.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Object[] constructorArguments, IInterceptor[] interceptors)
```

**Comment by stakx** [comment]
@RudeySH:

> this doesn't seem to work with the latest version of Castle.Core

The code shown in [the Stack Overflow question](https://stackoverflow.com/q/4205637/240733) contains several trivial errors and doesn't actually show the code that would produce a unique name, so it's unlikely that you used it verbatim.

Could you therefore please post a minimal code example showing *what exactly* does not work? Otherwise it is difficult to help.

(That aside, I'm sure you've noticed [@kkozmic's comment](https://stackoverflow.com/questions/4205637/castle-dynamicproxy-generated-class-names#comment4571364_4219073) saying that this probably isn't exactly a supported scenario. Lots of DynamicProxy's internals are `public`-ly accessible when perhaps they shouldn't be.)

**Comment by jonorossi** [comment]
> I want to change the name of the generated proxy type

As @stakx mentioned this isn't really supported and isn't in our documentation. What I'd like to know is why you want to change the generated name.

**Comment by RudeySH** [comment]
@jonorossi There's a type from a library I'm using that is meant to be sub-classed. However, I want to do this runtime, and multiple times. I'm using Castle.Core to achieve this. However, that type stores some stuff using static fields which interferes with my plan to sub-class it multiple times. When I create multiple proxies, they all have the same type name and thus have access to the same static fields. I want to prevent this by changing the type name of each proxy I generate.

I'll see if I can get a small example to reproduce the error.

**Comment by stakx** [comment]
> However, that type stores some stuff using static fields which interferes with my plan to sub-class it multiple times. When I create multiple proxies, they all have the same type name and thus have access to the same static fields. I want to prevent this by changing the type name of each proxy I generate. When I create multiple proxies, they all have the same type name and thus have access to the same static fields. 

I don't understand this. The proxies' type names have nothing to do with this, as far as I understand your situation. The problem here seems to be that they all derive from the same base class, so of course they will all have access to that base class' members, including any static fields.

Let's say you have:

```csharp
abstract class Base
{
    protected static object staticField;
}
```

You can have as many subclasses of `Base` as you want, but `Base.staticField` will still exist exactly once. It belongs to the `Base` class, not to the subclasses; it won't get "cloned" once per subclass. Neither the number of subclasses nor their names will change this fact, so it seems unlikely that substituting your own `INamingScope` would do any good.

Static fields only ever "multiply" when contained in generic types. So if you had in fact a `Base<T>` instead of `Base`, then DynamicProxy will *already* take care to name each proxy type differently when proxying different instantiation of `Base<T>`. So again, in this case, there's no benefit in substituting your own `INamingScope`.

Could it be that you actually want to "clone" `Base` *itself* instead of subclassing it?

```csharp
class Base1
{
    protected static object staticField;
}

class Base2
{
    protected static object staticField;
}

…
```

If so, DynamicProxy is the wrong tool for the job... it cannot do that.

**Comment by RudeySH** [comment]
> Static fields only ever "multiply" when contained in generic types.

I thought this applied to non-generic subclasses of a type as well. I am wrong.

Either way, the type I'm trying to create multiple proxies from does some sort of caching based on the type's name. I'm running into unexpected issues when multiple proxies have the same type name. I was able to confirm these issues are gone when I get Castle.Core to give the proxy a different type name each time. I achieved this by returning a random name every time `GetUniqueName` is called, by using `return suggestedName + Guid.NewGuid().ToString("N");`. However, this goes directly against the documentation:

> Implementers must return deterministic names, that is when `GetUniqueName` is called twice with the same suggested name, the same returned name should be provided each time. Non-deterministic return values, like appending random suffices will break serialization of proxies.

Any attempt to make my implementation of `GetUniqueName` return deterministic names results in the `ArgumentException` I mentioned earlier, which is why I opened this issue. For example, only calling `Guid.NewGuid()` once on each `INamingScope` would result in deterministic names, because calling `GetUniqueName` twice would return the same Guid, but this results in the exception.

> Could it be that you actually want to "clone" Base itself instead of subclassing it?

I guess I'm trying to subclass it AND "clone" (or copy-paste) the base class. The class is meant to be subclassed, and supports multiple subclasses of it, but unexpected issues arise when multiple subclasses have the same type name. I thought static fields were to blame but I misunderstood how they work, now I suspect there is caching on type name implemented by the subclass in question.

To be more direct. the class I'm trying to subclass dynamically using Castle.Core is `System.Data.Entity.DbContext` from Entity Framework 6. I'm not sure if mentioning this is any helpful to the discussion, though. I'm sure someone reading this might think there's no point in doing so, because it's not the way EF is meant to be used or something like that. I'd like to avoid having to thoroughly explain my exact business problem, but if it's necessary let me know.

**Comment by stakx** [comment]
If `DbContext` does caching by type *identity*, then you can follow @jonorossi's suggestion above. Types from different `ProxyGenerator`s will have same names but be in different assemblies and therefore have different identities.

If `DbContext` does caching based on (string) *name* alone then you might be out of luck.

Here's something for you to try instead of your current `INamingScope` approach:

1. Use `ModuleScope.DefineType` to define empty ("marker") interface types with a unique name, for example: 

   ```csharp
   Type GetSaltInterfaceType()
   {
       return proxyGenerator.ProxyBuilder.ModuleScope
           .DefineType(
               inSignedModulePreferably: true,
               name: "_" + Guid.NewGuid.ToString("N"),
               flags: TypeAttributes.Public | TypeAttributes.Abstract | TypeAttributes.Interface)
           .CreateType();
   }
   ```

2. When you create a subclass of `DbContext`, specify a new interface type created as shown above (you need to create a fresh one per subclass!) as an additional interface to implement. This should give the proxy type a unique identity in DynamicProxy's type cache, and therefore also a unique name.

   ```csharp
   proxyGenerator.CreateClassProxy(typeof(DbContext), new[] { GetSaltInterfaceType() }, ...);
   ```

Note that this is a pretty weird use of DynamicProxy. I haven't tested the above, but you might want to give it a try.

**Comment by stakx** [comment]
(And just as an aside, regarding that bit of documentation you mentioned:)

> [W]hen `GetUniqueName` is called twice with the same suggested name, the same returned name should be provided each time.

That bit of documentation should be updated, because it is phrased inaccurately. In fact, when called twice with the same suggested name, `GetUniqueName` *must not* return the same name. It would be more accurate to say: When repeatedly called with the same suggested name, `GetUniqueName` must deterministically produce the exact same sequence of unique names.

**Comment by RudeySH** [comment]
> You could however create multiple `ProxyGenerators`, each will have their own `AssemblyBuilder`, dynamic assembly and cache.

I tried using a new instance of my proxy generator for every proxy I wanted to generate, but that didn't solve my issue with `DbContext`. Actually, I *must* use a new instance of my proxy generator each time because otherwise my logic in `INamingScope.GetUniqueName` doesn't run for each proxy. So...

> If DbContext does caching based on (string) name alone then you might be out of luck.

This is probably the case here.

> When repeatedly called with the same suggested name, `GetUniqueName` must deterministically produce the exact same sequence of unique names.

The best I can come up with is this:

    private static readonly Dictionary<string, int> Counters = new Dictionary<string, int>();

    public string GetUniqueName(string suggestedName)
    {
        Counters.TryGetValue(suggestedName, out var counter);
        Counters[suggestedName] = ++counter;
        return suggestedName + counter;
    }

However, this isn't really deterministic, is it? The counters will just keep increasing and increasing until the application is restarted. This works for me though. This seems like a better solution than the salt interface.

Side note, I only just realized that my use case itself goes directly against the documentation. Having the naming scope return the same sequence of names is the opposite of what I want, because I need multiple instances of the same proxy generator to return different names each time.

**Comment by stakx** [comment]
@RudeySH: Forget about `INamingScope`. It really won't help you solve this.

DynamicProxy *only* calls `GetUniqueName` when it cannot find an already generated proxy type in its cache. That's why you need a new `ProxyGenerator` so that `GetUniqueName` gets called every time, because the cache will always be empty.

Have you tried my other suggestion? It should work with a single `ProxyGenerator` instance. What it essentially does is to enforce cache misses so that you get distinct & differently named proxy types.

**Comment by RudeySH** [comment]
The unique interface method works like a charm! I'll probably use that over having a custom `INamingScope` with a non-deterministic implementation.
