### ISSUE TITLE
GC problem on Proxy Creation

### ISSUE THREAD

**Issue by mikelneo** [castleproject/Core#386]
I get performance issue in a programm using Proxy generation. I use perfview fo diagnostic and find out that proxy creation involve many GC string allocationns wich result in too many garbage collections.

![gc_castle](https://user-images.githubusercontent.com/15369778/41609388-54c5fad0-73f3-11e8-82eb-417ba11c8d6e.png)

So reason is TypeUtil.Sort which uses "AssemblyQualifiedName" which do a string.concat. 
Why there is a need to sort interfaces? And is there a way to to this without AssemblyQualifiedName?

**Comment by TimLovellSmith** [comment]
@mikelneo Great issue - I definitely don't think string concatenations should be necessary during sorting - or at least not as part of the comparator, as currently written

Looks like the problem is here:

https://github.com/castleproject/Core/blob/fd0a0e8fc681680770ea1a9237155f60f718c646/src/Castle.Core/DynamicProxy/Internal/TypeUtil.cs#L246

And it would be because Sort is calling a lambda function *comparator* which calls AssemblyQualifiedName, instead of using e.g. LINQ OrderBy with a selector, or building a sorted dictionary, or just sorting without building the AssemblyQualifiedName.

**Comment by TimLovellSmith** [comment]
PS I don't know why they are sorted... but I would hazard a guess that one reason might be so that the interfaces are always returned in a consistent order?

**Comment by stakx** [comment]
Neither do I, and I've asked myself the same thing in the past. Here's three possibilities I've considered. Hopefully, someone who's been with DynamicProxy for a longer time than I can give a more satisfactory answer.

1. Totally wild guess: Perhaps this has to do with establishing certain guarantees such that serialization becomes a deterministic process.

2. Another guess: Perhaps interfaces from the same assembly need to be adjacent to one another for DynamicProxy to process things properly.

3. The order in which implemented interfaces are listed on a type affects the performance of interface  method calls&mdash;you'll see them tweak BCL types that way over at the CoreFX repo&mdash;but this does not apply here since we're basically sorting in alphabetical order here, which has no obvious correspondence to performance.

Interestingly, none of the unit tests fail if the sorting operation is simply commented out (but of course that could just mean that test coverage is insufficient).

**Comment by mikelneo** [comment]
I think the reason for sorting is CacheKey class, Equal override uses:
```csharp
for (var i = 0; i < interfaces.Length; i++)
{
	if (!Equals(interfaces[i], cacheKey.interfaces[i]))
	{
		return false;
	}
}
```

Although, not great solution, I think ImmutableHashSet<T> and Contains will give better performance then sorting over AssemblyQualifiedName.

**Comment by stakx** [comment]
That explanation seems a lot more plausible than my guesses. :lol:

If so, keep in mind though that a cache is likely to receive more reads than writes, so a slow sort upon writing may still pay off in the form of faster lookups later on. (Not saying that the current sorting is ideal, I wouldn't be surprised if this could be optimized.)

**Comment by mikelneo** [comment]
> a cache is likely to receive more reads than writes
@stakx not realy so in this case, CacheKey creates every time to find that proxy with same params already exists. So sorting occured every time proxy creates. See ClassProxyGenerator.GenerateCode.

**Comment by stakx** [comment]
@mikelneo - Yes, that's right, you have to build *one* cache key for the particular lookup alright&mdash;but all the *other* `CacheKey`s in the cache have already been made ready for a fast comparison. (I would almost bet that comparing two pre-sorted arrays is faster than comparing two unsorted sets on the fly.) Of course, the number of on-the-fly comparisons of unsorted interface type sets could be kept low by choosing a good hashing function for `CacheKey`.

There are obviously many ways how one could go about optimizing here; the important thing would be to actually *measure* (i.e. benchmark) which optimizations work well in various real-world usage scenarios.

**Comment by mikelneo** [comment]
I propose to change sorting like this:
```csharp
private static Type[] Sort(ICollection<Type> types)
{
	return types.OrderBy(_ => _.FullName)
		.ThenBy(_ => _.GetTypeInfo().Assembly.FullName).ToArray();
}
```

This way there is no extra GC activity, sorting works like current and it is a bit faster if beleave my test in BenchmarkDotNet (attach results).

[Sorting-report.xlsx](https://github.com/castleproject/Core/files/2118939/Sorting-report.xlsx)

**Comment by TimLovellSmith** [comment]
@mikelneo That algorithm looks better from perf POV. It still has to do some allocations to handle the ToArray(). You could still use Array.Sort, if you wrote a comparator function that compares equivalently to this, and that would probably be even faster than using LINQ. I think you might be changing the sort ordering for types in different assemblies but that might not matter to anyone?

**Comment by fir3pho3nixx** [comment]
> You could still use Array.Sort, if you wrote a comparator function that compares equivalently to this, and that would probably be even faster than using LINQ

+1

**Comment by fir3pho3nixx** [comment]
>  You could still use Array.Sort, if you wrote a comparator function that compares equivalently to this, and that would probably be even faster than using LINQ

+1
