### ISSUE TITLE
Activator.CreateInstance(generatedType) in ProxyGenerator may be thread unsafe

### ISSUE THREAD

**Issue by TimLovellSmith** [castleproject/Core#390]
Per #193 creating a new issue to track a hypothetical bug in ProxyGenerator calling Activator.CreateInstance without holding the lock that guards against races with Reflection.Emit.

>>Are you saying that the Activator.CreateInstance(generatedType) in ProxyGenerator must execute while a read lock is held?

>@stakx that might possibly be enough to fix it for some of the stacks we've seen, like this one:

```
at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, IInterceptor[] interceptors)
at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget(Type interfaceToProxy, IInterceptor interceptor)
at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget[TInterface](IInterceptor interceptor)
at NetCoreRepro.ProxyFactory.CreateProxyT in C:\work\CastleCore193Repro\NetCore\NetCoreRepro\ProxyFactory.cs:line 13
at NetCoreRepro.ToDuplicate.Test697.DoSomething() in C:\work\CastleCore193Repro\NetCore\NetCoreRepro\Generated\Test697.cs:line 12
```

>but I do not feel hopeful that it is going to fix all the other cases, because from the stack it seems like maybe they are triggered by JIT, rather than type loading or instantiation.

I'll create an issue specifically around `Activator.CreateInstance(generatedType)` and we can try out what fixing it does.

**Comment by stakx** [comment]
I should've added an explanation in #193 *why* I find it unlikely that this will be the solution (but by all means, do give this a try and report your findings! :-)

1. I have a branch in my clone of @BrunoJuchli's `NetCore/` repro where I've replaced DynamicProxy with plain Reflection.Emit code. Obviously I also need an `Activator.CreateInstance` call in there. The thing is, I've never been able to reproduce any errors once DynamicProxy is gone. So `Activator` doesn't appear to be the culprit or I'd still have seen the error.

2. If I understand Reflection.Emit more or less correctly, then it can benefit from one nice property of IL: No two types share any IL metadata table entries. Each type that is newly generated gets its own independent set of table rows, which are appended at the end of the preexisting type's rows (which remain unchanged). Therefore, at least in theory, Reflection.Emit shouldn't be able to affect types that have already been "baked" (i.e. types for which you have received a `Type` from a call to `TypeBuilder.CreateType`).

   To me, some of the errors @BrunoJuchli posted in #193 suggest that something went wrong at the time when Reflection.Emit did its work: Note the incorrect type names such as `System` or `System.Reflection.System.Reflection`; or the fact that a type is linked to the wrong assembly. That is, the IL metadata tables contain the *wrong* string heap indexes and metadata tokens, but not totally *invalid* ones (otherwise we'd probably see totally garbled type names). So what I'm suspecting at this point is that DynamicProxy somehow triggers two concurrent calls into Reflection.Emit, causing some kind of race with metadata token / string heap index lookup.

That being said, let me know how you're experiment goes!

**Comment by stakx** [comment]
@TimLovellSmith - It appears that you're on to something. According to https://github.com/dotnet/coreclr/issues/18635#issuecomment-400019820, `Activator.CreateInstance(typeFromDynamicModule)` should be completely safe even when new types are being emitted into the same dynamic module. Yet that doesn't appear to be the case in practice.

That being said, I'm not yet convinced that putting a lock around`Activator.CreateInstance` is the right solution. I've added some feedback to your two PRs #392 and #393 to explain why.

**Comment by BrunoJuchli** [comment]
To extend on @stakx comment:
Given:

    Foo foo;
    lock(globalLock)
        foo = Activator.CreateInstance<Foo>();
    foo.DoSomething();

The `BadImageFormatException` are observed to occur sporadically at both, `Activator.CreateInstance` *and* `foo.DoSomething`.

So putting a lock around `Activator.CreateInstance(...)` is, by itself, not good enough.

**Comment by stakx** [comment]
@TimLovellSmith: I'd like to also close this issue. While I have come to agree with the suspicion you've expressed in this issue's title, we've also reached the conclusion that it should not (and cannot) be us (DynamicProxy) to fix a possible problem in the runtime. To quote #392

> Microsoft have already stated that they expect Activator.CreateInstance with dynamic types should not have any threading constraints, any required locking on internal runtime structures for mutations should be performed by the runtime.

**Comment by stakx** [comment]
@TimLovellSmith: I'd like to also close this issue. While I have come to agree with the suspicion you've expressed in this issue's title, we've also reached the conclusion that it should not (and cannot) be us (DynamicProxy) to fix a possible problem in the runtime. To quote #392

> Microsoft have already stated that they expect Activator.CreateInstance with dynamic types should not have any threading constraints, any required locking on internal runtime structures for mutations should be performed by the runtime.
