### ISSUE TITLE
Add PCL assembly to the NuGet package

### ISSUE THREAD

**Issue by adamralph** [castleproject/Core#41]
I'm just throwing this out there although I've no idea if it's possible.

Ideally it would target the earliest versions of everything, i.e. net40, win8, sl4 and wp7 but if some or all of those need to be bumped to later versions, or if one of win8 or wp7 needs to be dropped then so be it. The idea is how to support as wide as possible and as early as possible, keeping the effort involved reasonable.

The reason I'm raising this is that we've had a few requests to support more platforms in FakeItEasy but Castle.Core is the restricting factor. We can only support the platforms which Castle.Core supports.

**Comment by weitzhandler** [comment]
Can you please add at least support for modern Xamarin PCLs (Profile 44), that target only UWP, Droid and iOS?

**Comment by jonorossi** [comment]
> Can you please add at least support for modern Xamarin PCLs (Profile 44), that target only UWP, Droid and iOS?

@weitzhandler as you can see in this thread and others like #162 it hasn't been possible to target UWP for Windows 8.x in the past because of missing `System.Reflection.Emit` APIs we require, however according to the [.NET Platform Standard v1.3](https://docs.microsoft.com/en-us/dotnet/articles/standard/library) docs it is supported on the following:

- Xamarin.iOS 10.0+
- Xamarin.Android 7.0+
- Universal Windows Platform 10.0+

Castle Core v4.0 supports .NET Standard 1.3, we won't be adding specific support for Portable Class Libraries, however you may be able to consume those assemblies in your Xamarin projects depending on how the tooling works.
