### ISSUE TITLE
CI build server platform consolidation

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#441]
We are using a mix of AppVeyor (for Windows) and Travis CI (for Linux), and recently both platforms have added the other operating system they didn't have previously. I think it is about time we look at just moving things to one service.

With [what is happening with Travis CI last month after being acquired](https://www.reddit.com/r/devops/comments/at3oyq/it_looks_like_ibera_is_gutting_travis_ci_just_a/) and the fact we lost all our history with the move to .com, I'd be a little wary of moving to Travis.

I think since we run all .NET Framework and .NET Core builds on AppVeyor, do releases and use the NuGet feeds; and only the Mono and .NET Core ones on Travis, we should just bring the Linux ones to AppVeyor to simplify things.

Note that we do releases from AppVeyor, so we need to make sure the Linux build doesn't also try doing releases when we tag a build. Not sure if we should add another job for making the release or we do something else, just something to be aware of.

Thoughts? Anyone interested in tackling this?

**Comment by stakx** [comment]
@jonorossi, I've been thinking the same. I've run a few early experiments, see [stakx/appveyor-sandbox](https://github.com/stakx/appveyor-sandbox) and experimented with its build matrix feature. That repo builds a simple multi-targeting library and runs unit tests. It should be possible to only push to NuGet for one specific build job.

There's quite a lot more to do, and it's not exactly my favourite thing to spend time on 😄 so I'll happily defer to anyone else who actively wants to work on it. Otherwise I might eventually get around to it.

**Comment by jonorossi** [comment]
@stakx I hadn't seen your repo. We also have our NVelocity build on AppVeyor on both Windows and Linux: https://github.com/castleproject/NVelocity/blob/master/appveyor.yml
