### ISSUE TITLE
SmtpClient should be disposed in EmailSender

### ISSUE THREAD

**Issue by kkozmic** [castleproject/Core#46]
See http://issues.castleproject.org/youtrack/issue/CORE-47 for more details

**Comment by kkozmic** [comment]
Bump.

Any ideas on this?

**Comment by dalefrancis88** [comment]
Sorry, forgot about this. I am actually not working at the moment. Packing up to head back to Australia.

I have some spare time so i'll check this out

**Comment by jonorossi** [comment]
@dalefrancis88 do you still have any interest in the `SmtpClient`? Did you end up joining us in Australia?

**Comment by dalefrancis88** [comment]
I did, I am in Melbourne now. Will check this out tomorrow.

**Comment by dalefrancis88** [comment]
Hey guys, checked this out a bit but feel bad since i've blown you off a bit, i am not sure if i am going to have the time to check this out in real detail

**Comment by jonorossi** [comment]
@dalefrancis88 no problem, just trying been trying to chase up whether logged issues are actually affecting people and clean out our issues. Were you ever getting the same `WebException` as the OP or just looked at this task to contribute?

**Comment by dalefrancis88** [comment]
Was just looking to contribute, i chatted to @kkozmic about a year ago saying that I wanted to contribute where i could and to help build up CW. I use it a lot and wanted to try to help where i could

**Comment by jonorossi** [comment]
@dalefrancis88 feel free to jump on other issues, we definitely need someone to help out with Windsor.

I think we should just close this issue since there has only been one report many years ago, it isn't clear what the actual problem even is, and this class is very rarely if ever used by users. The value for money just isn't there, if we get another report of this affecting someone we'll reopen.
