### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by blairconrad** [castleproject/Core#48]
As @kkozmic mentiones in FakeItEasy/FakeItEasy#179,

> the whole release process for Castle is manual, therefore requires some time aside to actually do it.
> Ideally, it'd be fully automated, so there's a lot that can be done there to improve it.

What can we do about that?

@castleproject/owners, I took a desultory look around the project for some sort of "how to release", but couldn't find anything. Did I miss it?
Either way, I'm keen to help make releasing easier, if anyone's interested in helping me understand the process. Let's chat.

**Comment by kkozmic** [comment]
Do we want to tackle any more of the manual steps? Also, a bit late but huge thanks @blairconrad for the effort here!

**Comment by blairconrad** [comment]
Ha, thanks. It was a pleasure.

I'd be happy to help with some stuff, if you think I can. Schedules a bit funny now, but if you don't mind slow work, I could try something.

Not sure what's automatable any more…
Possibly (referencing my list 2 comments ago)

* 1 - finding out the latest Core build could be done on _every_ Windsor build, I suppose. Or roll it into a command that will be executed below…
*  2ish (a human would need to pick the version number)
*  4 (semi-automated, the tag could be generated from Settings.proj)
* 5 (semi-automated - invoke curl or wget or something?)
* 6 we could conceivably have TeamCity publish, especially if it could figure out that it's building from a tag commit or something
* 7 - there's probably an Octokit function for this, so it could at least be a button push. Hmm. Is the only reason we're downloading the artifacts to push them? Then this step could obviate the need for the download in step 5?

3, 8, and 9 feel very humany to me. But I could be wrong.

What's yer big pain point? How would you _like_ it to work?

**Comment by kkozmic** [comment]
Hey @blairconrad 
I don't mind it taking a bit of time. I can't dedicate too much to doing it myself, so any help is welcome and appreciated :)

You're right, most of those still require some manual work.

In terms of how far it can be pushed I was thinking about a process somewhere along the lines of:
* set things up locally (Core reference for Windsor), update `settings.proj`, `changes` and `breakingchanges` files
* commit, tag and push
* Have TeamCity push to nuget and github (either implicitly, based on the tag, or explicitly as a manually triggered build in TC... although I'm not sure how well we can lock down the permissions here so that random people don't randomly push releases :)
* user group/twitter announcement could technically be automated with something like IFTTT I guess. Low priority
* updating the website would probably stay manual
* Doco is now part of the repo so hopefully would be brought up to date as part of the code changes.


Thoughts/ideas? /cc @castleproject/owners

**Comment by jonorossi** [comment]
I think trying to automate much more via TeamCity is going to be a lot of work, especially that there are quite a few manual steps in there. Next time I do a release I'm happy to put together a script that you can run on your own machine which could prompt you to complete manual tasks and prompt for credentials.

**Comment by kkozmic** [comment]
Sounds good.

On Fri, 11 Sep 2015 13:00 Jonathon Rossi <notifications@github.com> wrote:

> I think trying to automate much more via TeamCity is going to be a lot of
> work, especially that there are quite a few manual steps in there. Next
> time I do a release I'm happy to put together a script that you can run on
> your own machine which could prompt you to complete manual tasks and prompt
> for credentials.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/castleproject/Core/issues/48#issuecomment-139436889>.
>
-- 

sent from my phone
Krzysztof

**Comment by blairconrad** [comment]
Man, 19 days? Time flies.
@jonorossi, I see you've self-assigned, but if you like I could still try to pick off small pieces from time to time.
One thing I'd wondered about is the desired toolset. I'm used to (from FakeItEasy land) working with rake to set versions, create tags, update releases, and whatnot, but am happy to work with something else.
It seems that .cmd files are the preferred ways to build. Would we like something cmdy that we could have 
"commit, tag and push", to steal one of @kkozmic's steps?
In that case, we may need to take other (development) dependencies for tools, specifically to read versions out of `settings.proj` and whatnot.
Or we could build our own tiny utilities.

An alternative, if we're still considering performing releases from Windows, would be Powershell scripts, which would let us leverage XML readers and so on.

Thank.

**Comment by blairconrad** [comment]
@jonorossi, I think #241 is going to subsume this issue. Shall we close?

**Comment by jonorossi** [comment]
Yep, closing.
