### ISSUE TITLE
Method with return type List<long> never go through proxy

### ISSUE THREAD

**Issue by Armageddonw** [castleproject/Core#487]
In c++/clr, if you create a class with `List<long>^` return type, Interceptor is never invoked and there is no exceptions/errors thrown. Just silently invokes method, ommiting Interceptor.
Changing return type to `List<int>^` solves the issue.

```cpp
class ManagedClass
{
public:
    virtual System::Collections::Generic::List<long>^ Foo() { /* ... */ } //Not invoking interceptor
    virtual System::Collections::Generic::List<int>^ Boo() { /* ... */ } //Invoked interceptor
protected:
    ManagedClass() {};
}
```

Can it be somehow related to c# long type being 64 bytes and c++ long being 32 bytes?

**Comment by stakx** [comment]
I don't think so. I'm suspecting custom modifiers in the IL metadata method signatures, C++/CLI makes use of them quite a bit.

You're not running your code on .NET Core 1.x... are you?

**Comment by Armageddonw** [comment]
I'm running this code on standard .Net Framework 4.6.2

**Comment by stakx** [comment]
Could you perhaps upload here a compiled C++/CLI assembly containing just the type you're trying to proxy? (I'm asking because I currently don't have the C++/CLI compiler installed.)

**Comment by Armageddonw** [comment]
I cannot upload original assembly, but, I've prepared project with only this one class:
[OnlyAssembly.zip](https://github.com/castleproject/Core/files/4388995/OnlyAssembly.zip

And also simple console reproduction program:
[ReproConsole.zip](https://github.com/castleproject/Core/files/4388996/ReproConsole.zip)

(Both sources and compiled output)

**Comment by stakx** [comment]
Thanks. I couldn't use your assembly directly due to some "assembly not found" exception, so I extracted the `ManagedClass` type using `ildasm` and recompiled the assembly using `ilasm` (with some unnecessary C++/CLI specific stuff removed).

[Repro.zip](https://github.com/castleproject/Core/files/4389690/Repro.zip)

I've also included my repro and the dynamic assembly generated by DynamicProxy.

As I suspected, the difference between the two methods is that one carries a `modopt(System.Runtime.CompilerServices.IsLong)` in its method signature (for the return type's generic argument), while the other does not. For some reason, DynamicProxy drops that modopt from the signature so we end up with two non-identical `Foo` methods: one in the base class, and a proxied one in the proxy class. The repro code then calls the one in the base class since the C# compiler *does* include the modopt in the call signature.

Looks like a bug to me, either in DynamicProxy, or in the .NET Framework. It's possible that System.Reflection does not report the modopt correctly because it's nested "inside" a type. Will need to take a closer look soon.

**Comment by stakx** [comment]
> It's possible that System.Reflection does not report the modopt correctly because it's nested "inside" a type. 

And indeed, that is exactly what is going on here. Custom modifiers can only be discovered and applied at the `ParameterInfo` level, but not at the `Type` level, as a previous code owner for System.Reflection.Emit mentioned in https://github.com/dotnet/coreclr/pull/17881#issuecomment-387114966.

In this case,there is simply no way for DynamicProxy to discover and replicate the necessary `IsLong` custom modifier, because it isn't applied to the return type as a whole, but to a type nested inside it.

As long as DynamicProxy is built on top of System.Reflection[.Emit], there is nothing we can do about it.

**Comment by stakx** [comment]
While this probably classifies as a bug, I'm going to close this for now since there's nothing we can do about this (as explained in my above post).
