### ISSUE TITLE
[Question] Is it safe using original MethodInfo.Invoke() to call dynamic proxy?

### ISSUE THREAD

**Issue by PMExtra** [castleproject/Core#489]
I'm developing a RPC library.

I want to know is it safe using original MethodInfo.Invoke() to call dynamic proxy like below:

```CSharp
[Interceptor(typeof(LoggingInterceptor))]
public class DemoClass
{
    public virtual void HelloWorld()
    {
        Console.WriteLine("Hello World!");
    }
}

[Fact]
public void ReflectCallDynamicProxyTest()
{
    try
    {
        var method = typeof(DemoClass).GetMethod(nameof(DemoClass.HelloWorld));
        Assert.NotNull(method);

        var demo = _container.Resolve<DemoClass>();
        Assert.Empty(LoggingInterceptor.Calls);
        method.Invoke(demo, null);
        Assert.Single(LoggingInterceptor.Calls);
        Assert.Equal(nameof(DemoClass.HelloWorld), LoggingInterceptor.Calls.Single());
    }
    finally
    {
        LoggingInterceptor.Calls.Clear();
    }
}
```

The `LoggingInterceptor` is same as 
https://github.com/castleproject/Windsor/blob/4830718f99fd71e539133b34f9e54daa49049d6f/src/Castle.Facilities.WcfIntegration.Tests/Service/WcfServiceFixture.cs#L133-L145

The above test was passed. I just want to make sure it is correct at all times.

**Comment by stakx** [comment]
I cannot give a definite guarantee since I didn't write the runtime's reflection code such as `MethodInfo.Invoke` 😃, but AFAICT, the objects created by DynamicProxy are really regular .NET objects, so I don't see a reason why calling proxy methods through reflection should be any different from invoking other methods in the same way.

The only difference is that the proxy objects' types have been generated through Reflection.Emit instead of AOT by a compiler, but to my knowledge this shouldn't affect `MethodInfo.Invoke`.

If you don't quite trust the platform (CLR?) to do what it's supposed to, you could use a technique that we occasionally use in our own code base: We keep tests that test not our own code, but rather our assumptions about the underlying platform and technologies that we rely on. If those tests start failing, we know that something in the platform has changed and our assumptions are no longer (or never were) correct.

**Comment by PMExtra** [comment]
@stakx Thanks for your advice. I will keep some tests to ensure that.
But did you notice that my `method` (MethodInfo) is belongs `DemoClass`.
The `method.DeclaringType` is `DemoClass` instead `Castle.Proxies.DemoClassProxy`.
In my case, the `demo` is `Castle.Proxies.DemoClassProxy` that inheritance from `DemoClass`.
But I found there is another kind of proxy objects: Composition-based.
(https://github.com/castleproject/Core/blob/master/docs/dynamicproxy-kinds-of-proxy-objects.md)
So I'm not sure that.

**Comment by stakx** [comment]
> But did you notice that my method (`MethodInfo`) is belongs `DemoClass`.
The `method.DeclaringType` is `DemoClass` instead `Castle.Proxies.DemoClassProxy`.
In my case, the `demo` is `Castle.Proxies.DemoClassProxy` that inheritance from `DemoClass`.

If I understand you correctly, we need to answer to the question whether virtual dispatch will work correctly when using `MethodInfo.Invoke`. Let's run an experiment:

```csharp
class Base
{
    public virtual string GetSomething() => "something";
}

class Derived : Base
{
    public override string GetSomething() => "some other thing";
}

[Test]
public void MethodInfo_Invoke_performs_virtual_dispatch()
{
    var obj = new Derived();
    var getSomethingMethod = typeof(Base).GetMethod(nameof(Base.GetSomething));
    Assert.AreEqual("some other thing", getSomethingMethod.Invoke(obj, null));
}
```

And indeed, this appears to work as it should. This is expected, but should come as a surprise, because the [.NET API documentation for `MethodInfo.Invoke`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodbase.invoke) explicitly states (under the *Examples* heading) that... 

> [...] you cannot use the MethodInfo object from the base class to invoke the overridden method in the derived class, because late binding cannot resolve overrides.

That bit in the official documentation appears to be inaccurate.

>  But I found there is another kind of proxy objects: Composition-based.

Even with composition-based proxies, the generated proxy type has to be a class that derives from / implements the proxied type (`DemoClass` in your case). The different proxy types mainly differ in what the proxied (overridden) methods do.

All things considered, I think you can feel relatively safe using `Invoke` of the base method `MethodInfo` to call into a proxy.

**Comment by PMExtra** [comment]
Thanks a million for your help. It's so exact and professional, now I've fully understood about it.
