### ISSUE TITLE
Remove obsolete or redundant conditional compilation symbols

### ISSUE THREAD

**Issue by stakx** [castleproject/Core#501]
PR #495 removed approx. half of all conditional compilation symbols, but a few are left. This issue is a follow-up to @jonorossi [comment in said PR](https://github.com/castleproject/Core/pull/495#discussion_r426131150):

> After this is merged we can talk through these, more definitely need to go.

As to how more of those symbols can be removed, I would need to take a closer look. Right now, I'm assuming the following:

| Conditional compilation symbol | Remarks
| ---- | ----
| `FEATURE_SERIALIZATION` | Some serialization support was reintroduced in .NET Standard 2.0, e.g. all targeted platforms now support the `[Serializable]` attribute... but the binary serializer can't deal with e.g. `Type` nor delegates, so we can't easily enable this on .NET Core). But: This symbol is closely related to `FEATURE_APPDOMAIN` & `FEATURE_ASSEMBLYBUILDER_SAVE`, perhaps we could merge those into one.
| `FEATURE_REMOTING` | We can remove this iff we decide to give up support for remoting / `IsTransparentProxy` checks / `MarshalByRefObject`. (Is this something that's still used these days? For which types? I don't know.)
| `FEATURE_EVENTLOG` | We can remove this iff we deprecate `Castle.Core.Logging.DiagnosticsLogger`, which logs to Windows' event log.
| `FEATURE_SYSTEM_CONFIGURATION` | Tied to the facility in the `Castle.Core.Resource` namespace, which we could deprecate/remove.
| `FEATURE_TEST_PEVERIFY` | Needed for now, but I'm wondering whether we could offload the location of a PEVerify binary into the build scripts / MSBuild files. It might be neat to set an environment variable `PEVERIFY` to the PEVerify binary's location. (Setting an environment variable in an MSBuild project file might be non-trivial, but perhaps it [can be done](https://stackoverflow.com/a/20014410).)
| `FEATURE_TEST_COM` | .NET Core has some nominal COM support. It may not support functionality tied to `CoCreateInstance`, but AFAIK it *does* support COM interop and the COM attributes. So it may be possible to *reduce* usage of this attribute.

**Comment by jonorossi** [comment]
- `FEATURE_SERIALIZATION`: not sure, I'd have to look into it.
- `FEATURE_REMOTING`: I can't think of a good reason anyone would want do this today, there could be old code out there using `MarshalByRefObject`, but this is definitely one of those things that isn't moving forward with .NET 5.
- `FEATURE_EVENTLOG`: Need to get back to you on #394.
- `FEATURE_SYSTEM_CONFIGURATION`: Probably need to review how Windsor uses the whole resource thing, and maybe we move those classes into `Castle.Windsor.dll`.
- `FEATURE_TEST_PEVERIFY`: runtime check rather than conditional compilation sounds like a good idea, or maybe we can solely move to ILVerify (#506).
- `FEATURE_TEST_COM`: Interested to see what you come up with.

**Comment by stakx** [comment]
@jonorossi,

* `FEATURE_APPDOMAIN` and `FEATURE_REMOTING` &mdash; see the two small PRs that I just submitted.

* `FEATURE_TEST_COM` &mdash; I could cook up a C++ library that exports "[lightweight COM](https://stackoverflow.com/questions/38174095/what-exactly-is-lightweight-com)" components; that is, classes that adhere to COM's ABI and `IUnknown` protocol. Unlike with "true" COM, they wouldn't be instantiated by `CoCreateInstance` (which isn't available on Linux), but by P/Invoke-able functions also exported by said library. Once instantiated, these objects would be indistinguishable from regular COM objects, so we could map them to `[ComImport]` types in our test projects.

   We'd add the C++ source code to this repository, but not to the solution nor to the build script (to keep build requirements down). Our test projects would simply load precompiled x86/x64 DLLs of that library at runtime.

* `FEATURE_SERIALIZATION` &mdash; this might get messy. .NET Core supports binary serialization, but its `BinaryFormatter` cannot deal with all the types that the CLR version supports (see [this list of serializable types on Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization#serializable-types)). In some cases, we can simply drop the `FEATURE_SERIALIZATION` guards, in others we still need it (e.g. when a type contains a `Type` field). I'll happily submit a PR to remove a large number of unnecessary guards, but I don't yet know what to do about the remaining cases.

**Comment by stakx** [comment]
Let me see if I can get this straight. `FEATURE_SERIALIZATION` is a hodge-podge of at least 4 distinct concerns which we possibly need to untangle:

1. guards types that need to be serializable because they go in the `LoadAssemblyIntoCache` cache mappings blob (e.g. `CacheKey`, `ProxyGenerationOptions`, proxy generation hook types, or interceptor selector types) &mdash; i.e. types that support the load/save assembly scenario

2. guards code that's responsible for making generated proxy types serializable

3. guards code that's responsible for making generated invocation types serializable

4. guards exception types because MSFT says those should be serializable (so they can be ~~remoted~~ & cross app domain boundaries)

and with both (2) and (3), there's not just binary serialization to consider, but also XML serialization (and while we're at it, these days, we should at least mention `DataContractSerializer` and the very new `System.Text.Json` serializer).

With (1), I'm mostly concerned about serializability of `ProxyGenerationOptions` due to the potential presence of unserializable objects in the object graph&mdash;e.g. delegate mixins. Would we still mark PGO as serializable even when serializability cannot be guaranteed?

I'm not sure I fully grasp the importance of (2) and (3). I guess people might use mocking libraries to easily generate objects, then expect those to format just as nicely as the mocked/proxied base type for transmission across a wire... but would anyone want to *deserialize* a proxy or invocation? Not sure whether that's an important scenario but I tend towards "not important".

(4) should be easy, at least.

**Comment by jonorossi** [comment]
Great summary, and I too am not sure how much of everything is important.

(1) We've always had problems with serialization of types involved in the pre-generated assembly process, you can always have an interceptor, interceptor selector, mixin, etc that just can't be serialized properly, but no one has reported any defects with this in the last decade I can recall, so either so few people use this feature, people only use it for simple interceptors, or people worked out their problem and fixed their code to be serializable. My guess is it is mostly number 1, this feature has extremely limited use with partial trust web hosting a non-existent thing today, security is done by the OS not the runtime, not sure we can really offer this feature reliably anyway, too high of a risk of unbounded object graphs. We could consider dropping this and adding something better back in the future that was actually reliable if/when the need arises. What would we do for unit tests though.

(2) and (3) Maybe instead of DP doing this since we obviously don't support serialization for every possible different library someone could want to use (we've never had `JsonIgnoreAttribute`) we remove support and add a documentation page on how people can set that up for themselves with whatever serialization library they want to use? Maybe we don't even need that since most serialization libraries only serialize public properties, and we could just add `NonSerializedAttribute` for binary serialization. I do agree that this all seems a bit pointless because what is the use case, I do wonder if we just drop this support as a breaking change since we are having a new major version and add it back if someone presents a useful scenario which we can then document.

(4) There is probably little harm in just following the .NET Framework coding guidelines for making all exceptions serializable, but do you know if this is still the guidelines for .NET Core? I see for example `FileNotFoundException` in .NET Core implements the extra constructor and `GetObjectData`. It looks like all our exceptions except `InvalidProxyConstructorArgumentsException` are right.

**Comment by stakx** [comment]
I didn't quite dare suggest it myself, but I'm also favor of removing serializability for (1), (2), and (3) and only gradually add back the bits people really need. Could Windsor possibly be a roadblock here?

About unit tests, I suppose you're worrying about PEVerify? I could be wrong, but that ought to work even without serializability. `SaveAssembly` isn't in danger, it's `LoadAssemblyIntoCache` that would go away from the public API. I agree we'd want to keep `SaveAssembly`, refactoring and extending DP without being able to look at the generated types would be a pain.

Regarding (4), I guess framework exception types are still made `[Serializable]` and `ISerializable` so that the FCL code can be shared with Mono, which now sits in the same monorepo.

**Comment by stakx** [comment]
I am going to close this issue. I've removed as many conditional compilation symbols as is currently possible without removing actual features.

The discussion about whether or not serialization support should be removed probably deserves a dedicated issue.
