### ISSUE TITLE
Assemblies are not code signed

### ISSUE THREAD

**Issue by dickvdm** [castleproject/Core#533]
Assemblies (Castle.Core.dll) in nupkg are not code signed.

**Comment by stakx** [comment]
Maybe I am a bit conservative here, but may I ask: is this *actually* a problem for every-day use / consumption of the package? If so, why?

If I understand this correctly, someone would have to pay for a code signing certificate and renew it every now and then. I think there would have to be some real-world benefit to make up for those costs.

TBH I'm not totally convinced that it's worth it.

**Comment by mxmissile** [comment]
I've never understood this, with an open source package, you and just sign it yourself, unless I'm mistaken???

**Comment by stakx** [comment]
@mxmissile, who does the signing? And with what, some kind of certificate? What kind of certificate? Can I produce one myself, or do I need to get it from someone else? If there are several potential sources, which is the preferred one, and why? Does it cost something? If so, who pays? Does it have to be renewed regularly, and if so, how often? Does the certificate have to be kept in a safe place, and if so, where? How is that compatible with the idea open-source / open collaboration? Which collaborators can be trusted with access to the certificate? If there are several collaborators, who will be responsible for renewing?  If the certifcate needs to be renewed regularly, how to make that collaborator won't forget about it? How do you integrate the whole process with CI? etc.

Those aren't hypothetical questions. I don't have the answers, so if it were up to me to set up code signing, I'd have to find good answers to all of the above. So it seems a tad more complicated than _"just sign it yourself"_ as you said. :wink:

But I might be wrong. If it's truly a straightforward thing, perhaps you could prepare a PR?

**Comment by mxmissile** [comment]
@stakx I did not mean to imply signing the castle project, I meant simply that the OP could do it themselves, to be consumed by themselves.

**Comment by stakx** [comment]
@mxmissile, ah, I see... my apologies. I suspect it may be for similar reasons that projects aren't forked nearly as often as they could be: you'd have to "sync"/reapply your own work (here: code signing) every time a new version gets published upstream, and people (me included) may find it more convenient to have all the work done for them upstream.

**Comment by jonorossi** [comment]
I completely agree @stakx about code signing not being a simple process. The OP states they want the binaries not the package code signed, so that likely means Authenticode, however what about non-Windows OSs, it's not just the mechanism to sign it would also require selecting a CA that is supported across many OSs.

There is also NuGet package signing which likely would have better multi-OS support, however the docs just talk about CAs supported by Windows so maybe not: https://docs.microsoft.com/en-us/nuget/create-packages/sign-a-package

Lastly if we were going to get a code signing certificate we'd have to change our release process, we'd need to protect the private key, and since "Castle Project" isn't an organisation we wouldn't be allowed to get a certificate with that name, and we'd have to get individual certificate, and as you said people would have to trust that individual, but that is no different to now were I've pushed binaries for nearly a decade without people disassembling and reviewing each release before using it.

I still feel PKCS#7 code signing is the wrong method for OSS, and a PGP based approach where anyone is allowed to sign anything and publish their signature as a better method, that way your private key can be on a hardware device, you can sign a deterministic build locally and just publish the signature centrally, not supported in the .NET space but many others in the industry are going this way.

If we don't get a reply from the OP with more info or other users jumping in, I think we close this as won't fix for now.
