### ISSUE TITLE
Slow debugging

### ISSUE THREAD

**Issue by wocar** [castleproject/Core#539]
* **OS**: MacOS
* **IDE**: Happens with VS for Mac and with Jetbrains Rider. 

Im using AutoFac

Am I the only one with performance problems when debugging? Since I start debugging till the website is available it takes around 50 seconds.

I'm almost certain that it is because of the interceptors.  On the debug output I have the following message, sometimes it takes around 15 seconds. 

```
Loaded Assembly '<unknown>'
Loading module DynamicProxyGenAssembly2 in application domain 1:clrhost
Pdb file for assembly DynamicProxyGenAssembly2 was not found or failed to read
```

The catch is that if I run it without the debugger attached, it takes 3 seconds to boot. Anyone experiencing the same issue?

Related to: https://github.com/abpframework/abp/issues/6526
Related to: https://youtrack.jetbrains.com/issue/RIDER-51041

**Comment by maliming** [comment]
No one has reported such a problem. I think it has something to do with your environment.

**Comment by stakx** [comment]
@wocar, this is most likely a problem with your debugger's settings. I am guessing that it wastes a lot of time trying to fetch non-existent debugging symbols for `DynamicProxyGenAssembly2`. If you're using Visual Studio, go to _Debug_ &rarr; _Options_ &rarr; _Debugging_ &rarr; _Symbols_ and try either of these two approaches:

1. At the top, disable all checkboxes in the _Symbol file locations_ list; or
2. At the bottom, choose the option _Load only specified modules_ instead of _Load all modules, unless excluded_. 

Either of these should cause the debugger to load much fewer debugging symbols. It should no longer try to load symbols for `DynamicProxyGenAssembly2`.

Changing your debugger's settings is likely the only thing that can be done here.

**Comment by wocar** [comment]
Thank you for the support given. For anyone else wondering what might it be, I'm using Rider + MacOS disabled this feature:

![image](https://user-images.githubusercontent.com/9215073/102158265-b62d7f80-3e46-11eb-8ba4-1fe000d7e456.png)

And now instead of 30+ secs its like 8 secs. Thank you once again.

**Comment by lauxjpn** [comment]
You also want to make sure that you are _reusing_ your `ProxyGenerator` instance, so that dynamic types are not recreated over and over again.

See [Castle DynamicProxy](https://github.com/castleproject/Core/blob/master/docs/dynamicproxy.md) and [Performance advice for using Castle DynamicProxy in .NET web-apps](https://stackoverflow.com/a/6302758/2618319).
