### ISSUE TITLE
Please make Castle.Core.Internal.CollectionExtensions internal because it shows up in IntelliSense

### ISSUE THREAD

**Issue by jnm2** [castleproject/Core#560]
Both Visual Studio natively and ReSharper suggest extension methods they found in unimported namespaces from all directly or indirectly referenced packages. There are parentheses showing that they will add a `using` directive for that namespace if you select that extension method, but if you are moving quickly, you can end up with `using Castle.Core.Internal;` without noticing. Sometimes the first time you notice is many commits later or after submitting a PR. It's not pleasant to be stepping around these gotcha entries in IntelliSense.

**Comment by stakx** [comment]
I agree this class probably shouldn't be public (we've made a whole lof of internals internal already) so I'm all for it; but this won't solve the more fundamental problem, which is that IntelliSense shouldn't suggest extension methoss from unimported namespaces in the first place, esp. when the containing class is marked `EditorBrowsable.Never`; sort of defeats one of the original design goals of extension methods.

**Comment by jnm2** [comment]
IIRC `EditorBrowsable.Never` does work on each extension method. I wouldn't expect `EditorBrowsable.Never` on the class to come into play because it wouldn't come into play for contained static methods after you've already dotted off the class name.

**Comment by jonorossi** [comment]
> IntelliSense shouldn't just suggest any random extension method from unimported namespaces in the first place

My guess is that since people don't know what namespace the extension methods they want are in, IDEs need to suggest. For example, a user types `collection.Where(`, users want `using System.Linq;` automatically added.

Looking at `CollectionExtensions`'s history, it appears it was built for Silverlight where we had 2 conditional implementations, but that is obviously gone now. The 3 extension methods can probably all go, the other 2 non-extension methods could go somewhere more relevant.
