### ISSUE TITLE
How to get the orignal interface when use IInterceptor  to aop?

### ISSUE THREAD

**Issue by 835718973** [castleproject/Core#592]
when i use this to create a proxyobject and use the IInterceptor to aop,how can i get the proxy-interface(IPerson) at the intercept method?
`IPerson p = Generator.CreateInterfaceProxyWithTarget<IPerson>(new Person(), Interceptor);`
 `public void Intercept(IInvocation invocation)  `

**Comment by jonorossi** [comment]
`invocation.Method.DeclaringType` should get you `IPerson` in your example.

**Comment by 835718973** [comment]
`

    public interface IPerson
    {
        void Say();
    }

    public interface IStudent : IPerson
    {
    }

    public class Student: IStudent
    {
        public void Say()
        {
            //dosomething
        }
    }

IStudent p = Generator.CreateInterfaceProxyWithTarget<IStudent >(new Person(), Interceptor);

public void Intercept(IInvocation invocation);
`
How ablout this?
the invocation.Method.DeclaringType get the type of IPerson,but I want to get IStudent,the proxy interface.

**Comment by stakx** [comment]
@835718973, DynamicProxy does not currently offer any way to get back at the various parameters used during proxy creation.

**Comment by stakx** [comment]
@835718973 you could possibly retrofit that missing capability through a custom mixin, but this solution requires some additional work for each created proxy object. For example:

```csharp
public interface IProxyCreationParameters
{
    Type ProxiedType { get; }
    // ...
}

class ProxyCreationParameters : IProxyCreationParameters
{
    public Type ProxiedType { get; set; }
    // ...
}

var generator = new ProxyGenerator();
var options = new ProxyGenerationOptions();
options.AddMixinInstance(new ProxyCreationParameters { ProxiedType = typeof(IStudent), ... });
var proxy = generator.CreateInterfaceProxyWithTarget<IStudent>(new Student(), options, ...);

var proxiedType = ((IProxyCreationParameters)proxy).ProxiedType;
```

**Comment by jonorossi** [comment]
@835718973 assuming that you meant `new Student()` rather than `new Person()`. As @stakx said, this isn't possible. DynamicProxy can implement one or more interfaces on the proxy class for you if you specify the additional interfaces parameter, the single interface as a generic parameter is a convenience feature.

However you could do something like this:
```csharp
invocation.Proxy.GetType()
    .GetInterfaces().Where(if => if.Namespace != "Castle.DynamicProxy") // Make sure to skip IProxyTargetAccessor
    .First()
```

**Comment by 835718973** [comment]
I want to create a C/S application with grpc and Autofac. Dynamicproxy. On the client side, remote services can be called just like local services. The local service to the remote service is realized through the dynamic proxy of Autofac. Now I need to get the interface in resolve < interface > in the proxy in order to pass it to the remote service to restore the actual calling process. I have tried many methods. What I can achieve now is to register the type itself while registering the service, and then get the actual type of the proxy object in the interceptor, and directly parse the actual type on the server side to call it. However, on the server side, I have to register the type instead of just registering the interface.

**Comment by stakx** [comment]
@835718973, you're giving us a coarse description of your project, which involves a combination of several different technologies &mdash; unfortunately, we cannot get into that in detail, since the focus of this issue tracker is the development of Castle.Core. We've given you several hints at how you can get back at the proxied interface(s) given a DynamicProxy proxy object; what you do with that information, and how you integrate it with the other libraries in your project's tech stack, will be up to you.

If any of the above suggestions were unclear, please let us know and we'll try to clarify. Otherwise, I'm going to close this issue in a few days' time (since there's no immediate action we need to take in this project).
