### ISSUE TITLE
Inheritance of Attributes from Interface Members

### ISSUE THREAD

**Issue by bepursuant** [castleproject/Core#593]
Hello team - This might be an easy one to put to rest, I think I just need a castle expert to look at it.

I have [an issue](https://github.com/aloneguid/config/issues/107) with a separate project, and I think it comes down to something in the Castle proxy generation.

The root of the question is - _can Castle allow my generated proxy to inherit attributes from its source Interface?_  The linked issue has an example project demonstrating the disconnect.

**Comment by stakx** [comment]
Hi @bepursuant. I don't remember all the implementation details without looking them up, but off the top of my head:

As a rule of thumb, **DynamicProxy only replicates non-inherited custom attributes.** There is currently no mechanism or option to change that behavior. The only thing you _can_ do is globally specify (via [`Castle.DynamicProxy.Generators.AttributesToAvoidReplicating.Add(Type)`](https://github.com/castleproject/Core/blob/d88e94447150996973d947a150ffda5efc0c3c1c/src/Castle.Core/DynamicProxy/Generators/AttributesToAvoidReplicating.cs#L39)) custom attribute types that should not be replicated... but that is the opposite of what you need.

Your [`DescriptionAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.descriptionattribute)s will not be replicated because `DescriptionAttribute`s are inherited attributes. Let's check its definition:

```csharp
[AttributeUsage(AttributeTargets.All)]
public class DescriptionAttribute : Attribute
```

Its `[AttributeUsage]` does not explicitly specify `Inherited = false`, so the [default](https://docs.microsoft.com/en-us/dotnet/api/system.attributeusageattribute.inherited#property-value) (`Inherited = true`) applies.

Knowing this, you could try subclassing `DescriptionAttribute` and then reapply `[AttributeUsage]` with `Inherited = false`. If you then use that custom attribute type, DynamicProxy should replicate it on the generated proxy type.

Let's try this:

```csharp
using System;
using System.ComponentModel;
using System.Reflection;

using Castle.DynamicProxy;

var generator = new ProxyGenerator();

var foo = generator.CreateInterfaceProxyWithoutTarget<IFoo>();
var fooAttr = foo.GetType().GetProperty("Property").GetCustomAttribute<DescriptionAttribute>();
Console.WriteLine(fooAttr?.Description);

var bar = generator.CreateInterfaceProxyWithoutTarget<IBar>();
var barAttr = bar.GetType().GetProperty("Property").GetCustomAttribute<DescriptionAttribute>();
Console.WriteLine(barAttr?.Description);

public interface IFoo
{
    [Description("Some description.")]
    object Property { get; set; }
}

public interface IBar
{
    [NonInheritedDescription("Some description.")]
    object Property { get; set; }
}

[AttributeUsage(AttributeTargets.All, Inherited = false)]
public class NonInheritedDescriptionAttribute : DescriptionAttribute
{
    public NonInheritedDescriptionAttribute(string description) : base(description) { }
}
```

Not sure if this will help in your situation, but it may be worth a shot.

**Comment by stakx** [comment]
@bepursuant: has the above post answered your question? (If so, let's close this issue.)

**Comment by bepursuant** [comment]
@stakx - thanks so much for the thorough explanation and example resolution. This exactly solved my dilemma, with only three lines of code! Really appreciate the help! I've added the details to my original issue in the aloneguid/config project for anyone else looking at a similar issue.
