### ISSUE TITLE
Memory leaks in StrongNameUtil

### ISSUE THREAD

**Issue by arashjfz** [castleproject/Core#594]
In my project I found a memory leaks in **StrongNameUtil**  class

 ```csharp
  internal static class StrongNameUtil
	  {
		  private static readonly IDictionary<Assembly, bool> signedAssemblyCache = new Dictionary<Assembly, bool>();
 ```

It seams that **signedAssemblyCache**  has a problem and nothing is removed from it.
My memory analyzer says that There is millions of reference from **signedAssemblyCache**  key to **AssemblyBuilder** assembly
As I checked **signedAssemblyCache** was the only reference to that instance of **AssemblyBuilder** assembly. So a ConditionalWeakTable may fix this kind of problem

**Comment by stakx** [comment]
Hi @arashjfz, thanks for reporting this potential issue, and for the accompanying PR.

> It seams that `signedAssemblyCache` has a problem and nothing is removed from it.
My memory analyzer says that There is millions of reference from `signedAssemblyCache` key to `AssemblyBuilder` assembly

Am I understanding correctly that your memory analyzer claims that there are _millions_ of `AssemblyBuilder` objects? If so, something is seriously going wrong: there shouldn't be more than at most two of those per `ProxyGenerator`. So my first suspicion would be incorrect usage of `ProxyGenerator` &ndash; they are designed to be reused for many proxy creations; one shouldn't instantiate a new generator per proxy.

At least with the .NET Framework, the assembly cache in `StrongNameUtil` shouldn't be a problem because assemblies cannot be unloaded from memory... at least not before unloading the whole `AppDomain`, which would also reclaim the cache.

(There have recently been changes in .NET Core that means assemblies may be garbage-collected, but we don't currently support any of that; see e. g. #473.)

I'm suspecting that your PR, which changes `StrongNameUtil`'s cache to be based on a `ConditionalWeakTable` instead of a `Dictionary`, may therefore not help much (because the cache isn't the only thing holding on to loaded assemblies; they wouldn't be collected in either case), bit could in fact cause a performance degradation (at the very least because `ConditionalWeakTable` is likely less optimized for performance than `Dictionary`). So I am not convinced yet that we should make the change.

I think it would be important to know a little more about your memory analysis. Do you have a small repro code and instructions on how you performed the memory analysis?

**Comment by arashjfz** [comment]
@stakx Thanks for your reply, You are correct.  I Found the problem in my code and fix the situation that cause multiple assembly generation.
