### ISSUE TITLE
Log warning if multiple ProxyGenerators/ModuleScope used

### ISSUE THREAD

**Issue by kkozmic** [castleproject/Core#62]
There should usually be only one (or few) `ProxyGenerator` (and more specifically `ModuleScope`) in an application.

A common misuse is to `new` up a `ProxyGenerator` every time a proxy type is needed which effectively is a memory leak, and a significant performance hit.

We should log a warning if multiple (more than 10 perhaps) are created, possibly even throw an exception, although this would be a breaking change, so perhaps logging will suffice.

**Comment by kkozmic** [comment]
Any takers? This should be fairly easy to implement and would be useful to quite a few people

**Comment by stakx** [comment]
@kkozmic, my current PR #278 apparently violates the rule that only one `ModuleScope` should be used. This is "only" for unit tests. Could you perhaps do a quick review and let me know whether my use of an additional `ModuleScope` is inappropriate?

**Comment by jonorossi** [comment]
@stakx that pull request is fine.

This feature is probably unnecessary, I haven't see anyone on the mailing lists or Stackoverflow make this mistake in probably a decade, you'd notice the memory leak and performance hit of creating new proxy types each time so quickly, especially in a web app.

**Comment by stakx** [comment]
@jonorossi, thanks for the clarification!

**Comment by jonorossi** [comment]
As I mentioned in https://github.com/castleproject/Core/issues/62#issuecomment-311697412, people rarely make this mistake anymore because high memory usage especially in a web application would be really obvious and we have the warning on the home page of the docs (https://github.com/castleproject/Core/blob/master/docs/dynamicproxy.md).

I'm going to close this issue, because people are very unlikely to have even configured logging on the `ProxyGenerator` so wouldn't see the warning meaning this doesn't really produce much value.
