### ISSUE TITLE
Parameterless Constructor not needed 

### ISSUE THREAD

**Issue by janschmidmaier** [castleproject/Core#63]
When Creating a Proxy using `CreateClassProxyWithTarget` the Target must have a parameterless Constructor.
From my point of view, it would be easy sometimes, to be able to create a non initialized object, by calling
`object newObject = FormatterServices.GetUninitializedObject(type);`

```csharp
protected object CreateClassProxyInstance(Type proxyType, List<object> proxyArguments, Type classToProxy, object[] constructorArguments)
{
  try
  {
      if (constructorArguments != null && constructorArguments.Length != 0)
        return Activator.CreateInstance(proxyType, proxyArguments.ToArray());

      foreach (var ctor in proxyType.GetConstructors())
        if (!ctor.GetParameters().Any())
          return Activator.CreateInstance(proxyType, proxyArguments.ToArray());

      return FormatterServices.GetUninitializedObject(proxyType)
  }
  catch (MissingMethodException ex)
  {
    StringBuilder stringBuilder = new StringBuilder();
    stringBuilder.AppendFormat("Can not instantiate proxy of class: {0}.", (object) classToProxy.FullName);
    stringBuilder.AppendLine();
    if (constructorArguments == null || constructorArguments.Length == 0)
    {
      stringBuilder.Append("Could not find a parameterless constructor.");
    }
    else
    {
      stringBuilder.AppendLine("Could not find a constructor that would match given arguments:");
      foreach (object obj in constructorArguments)
      {
        string str = obj == null ? "<null>" : obj.GetType().ToString();
        stringBuilder.AppendLine(str);
      }
    }
    throw new InvalidProxyConstructorArgumentsException(((object) stringBuilder).ToString(), proxyType, classToProxy);
  }
}
```

**Comment by janschmidmaier** [comment]
Hi! Any news on that topic ? ;)

**Comment by kkozmic** [comment]
I'm not sure. What was the reason to remove the constructor again?

**Comment by janschmidmaier** [comment]
Hi!
Actually it is not about removing the constructor. We would like to have the chance, that the parameterless constructor is not needed. In that case using the .Net
`FormatterServices.GetUninitializedObject(type);`
would work perfectly. (From our point of view).
We would not need to have dummy constructor. Maybe this could be a special behaviour of `CreateClassProxyWithTarget` (or another, new method)

**Comment by kkozmic** [comment]
Right, I see.

What would be a scenario where that's preferable?

**Comment by janschmidmaier** [comment]
Let's say we have Class A, which needs an object of type B
`public class A {
  public A(B bObject) {
    _b = bObject;
 }
public bool SomeFoo() {
  // do sth. with _b
}
}

If you want to use a Proxy for example to log MethodCalling, you would need a parameterless constructor, which would poison your models, since A can not life without a B


I hope my thoughts are understandable.

**Comment by kkozmic** [comment]
I see. Thanks for clarifying.

I guess that's a reasonable expectation, although there are some complications once you look at what implementing it would require:
- the constructor on the proxy has extra arguments compared to the base constructor. If we were to allow creation of proxies without calling the constructor, those proxy-specific parameters would still have to be passed to the proxy object somehow, which probably implies adding some sort of `ProxyInit` method to the proxy class.
- `FormatterServices.GetUninitializedObject(type);` doesn't work in some cases (limited privilege) so that would need to be handled (not sure if we have anything to fallback to if the constructors aren't available, so at least the exception message would need to clearly explain the problem and suggest to pass the right constructor parameters)
- The proxy itself being a concrete implementation of a potentially stateful class you're proxying will not have its state intialised. This may lead to some odd behaviour in cases where proxy state gets used. This problem exists already, but is potentially made worse when we skip the constructor.

**Comment by jonorossi** [comment]
Be aware that .NET Core doesn't have the `FormatterServices` class, so this would need to be an opt-in feature only for desktop runtimes.

**Comment by kkozmic** [comment]
Ah good one. I didn't know that.

On Fri, 11 Sep 2015 at 13:23 Jonathon Rossi <notifications@github.com>
wrote:

> Be aware that .NET Core doesn't have the FormatterServices class, so this
> would need to be an opt-in feature only for desktop runtimes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/castleproject/Core/issues/63#issuecomment-139442939>.
>
-- 

sent from my phone
Krzysztof

**Comment by janschmidmaier** [comment]
oh I see :(
actually I didn't know that either.
Looks like we have a real specialty here :(

I guess it would work for us, but isn't that clean for everybody else
I would love to have that Feature, but I unterstand, if you have concerns

I would implement it myself, but somehow I can not compile the Code on gitHub.

**Comment by jonorossi** [comment]
It isn't in .NET Core because that class is for binary serialization which Microsoft is trying to kill especially that AppDomains don't exist in .NET Core. `GetUninitializedObject` also isn't going to work for CreateClassProxy.

@janschmidmaier feel free to log a new issue (or use the mailing list) with the problem you are having compiling the code.

**Comment by jonorossi** [comment]
I'm going to close this issue for now as it has stalled and this request is very specialised. Jump back in if this is still something you want to look at.
