### ISSUE TITLE
Can DynamicProxy intercept the finalizer?

### ISSUE THREAD

**Issue by javidsho** [castleproject/Core#630]
For a project, I have to know when a proxy object is getting finalized by the GC so that I can dispose some related resources. Is that possible using this library?

**Comment by stakx** [comment]
No, DynamicProxy does not intercept finalizers.

Without knowing the full history behind that design decision, I think it's quite sensible:

During finalization, i.e. inside a finalizer, one must assume that all references to other objects are no longer valid; that is, the referenced objects may already have been collected. This is because the order in which the .NET garbage collector reclaims objects is not deterministic (IIRC). As a consequence of this, only value-typed fields can be safely accessed in a finalizer. 

Therefore, DynamicProxy cannot safely intercept a finalizer, because there's no safe way to retrieve (and invoke) the proxy's interceptors.

You'll probably have to use a inheritance-based proxy and put your finalizer in the proxied class; but you won't be able to intercept it using DynamicProxy.

... perhaps implement the Disposable pattern and intercept `Dispose` instead?

**Comment by stakx** [comment]
Proxying (that is, intercepting) finalizers isn't impossible, it's just pretty pointless (generally speaking).

If you really wanted to, you could fork this project, remove [this line of code](https://github.com/castleproject/Core/blob/0176c319ea9feecf911e2fcf35319eaead866ea8/src/Castle.Core/DynamicProxy/Contributors/MembersCollector.cs#L216), and possibly implement a specialized method generator for finalizers (because, like I said above, the intercepted method call couldn't safely be sent through the interception pipeline as the objects making it up might no longer be alive).

**Comment by javidsho** [comment]
I don't even want to access any fields or other stuff. I just want to use it as a notification of when the object is collected. I'm using it in an RPC library to inform the remote party that some shared object is no longer necessary.
Anyways, thank you for the information.

**Comment by stakx** [comment]
> to inform the remote party

Sounds like you'd need to dereference an object reference in order to do so. Which is something that you generally shouldn't do in a finalizer. (Unless maybe that reference is stored in a static field.)

Anyways, I don't mean to force that point on you any more than I already did (sorry!)... good luck with solving that code puzzle! :-)
