### ISSUE TITLE
Proxies using Records derived from a base generic record broken using .NET 6 compiler

### ISSUE THREAD

**Issue by CesarD** [castleproject/Core#632]
Similar to what occurred in #601, when trying to mock (with Moq) records derived from a base generic record, an exception is thrown.

Repro code:

```csharp
var mock1 = new Mock<MyDerivedRecord>();
var mock2 = new Mock<MyDerivedGenericRecord>();

var a = mock1.Object;
var b = mock2.Object;

public abstract record MyBaseRecord
{
}

public abstract record MyBaseGenericRecord<T>
{
	public T Prop { get; set; }
}

public record MyDerivedRecord : MyBaseRecord
{
}

public record MyDerivedGenericRecord : MyBaseGenericRecord<int>
{
}
```

Variable `a` holds the mocked object as expected, but when initializing `b`, the following is thrown:

```
System.ArgumentException
  HResult=0x80070057
  Message=Type to mock (MyDerivedGenericRecord) must be an interface, a delegate, or a non-sealed, non-static class.
  Source=Moq
  StackTrace:
   at Moq.CastleProxyFactory.CreateProxy(Type mockType, IInterceptor interceptor, Type[] interfaces, Object[] arguments) in C:\projects\moq4\src\Moq\Interception\CastleProxyFactory.cs:line 66
   at Moq.Mock`1.InitializeInstance() in C:\projects\moq4\src\Moq\Mock`1.cs:line 307
   at Moq.Mock`1.OnGetObject() in C:\projects\moq4\src\Moq\Mock`1.cs:line 326
   at Moq.Mock`1.get_Object() in C:\projects\moq4\src\Moq\Mock`1.cs:line 281
   at Program.<Main>$(String[] args) in C:\Users\Cesar\source\repos\ConsoleApp1\Program.cs:line 11

  This exception was originally thrown at this call stack:
    System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
    System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
    Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.BuildType()
    Castle.DynamicProxy.Generators.BaseClassProxyGenerator.GenerateType(string, Castle.DynamicProxy.Generators.INamingScope)
    Castle.Core.Internal.SynchronizedDictionary<TKey, TValue>.GetOrAdd(TKey, System.Func<TKey, TValue>)
    Castle.DynamicProxy.Generators.BaseProxyGenerator.GetProxyType()
    Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(System.Type, System.Type[], Castle.DynamicProxy.ProxyGenerationOptions, object[], Castle.DynamicProxy.IInterceptor[])
    Moq.CastleProxyFactory.CreateProxy(System.Type, Moq.IInterceptor, System.Type[], object[]) in CastleProxyFactory.cs

Inner Exception 1:
TypeLoadException: Return type in method 'Castle.Proxies.MyDerivedGenericRecordProxy_2.<Clone>$()' on type 'Castle.Proxies.MyDerivedGenericRecordProxy_2' from assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is not compatible with base type method 'MyDerivedGenericRecord.<Clone>$()'.
```

_Originally posted by @CesarD in https://github.com/castleproject/Core/issues/601#issuecomment-1213625907_

**Comment by CesarD** [comment]
@stakx not sure if you were aware of this one.

**Comment by stakx** [comment]
@CesarD, sorry for not getting back to you sooner. I'll try looking into this in the next few days.

**Comment by CesarD** [comment]
Thanks so much!! 🤩🤩

**Comment by stakx** [comment]
Finally found some time to look into this today. As suspected, the root cause for this issue is the same as in https://github.com/castleproject/Core/issues/601#issuecomment-1125943775. We solved that other issue by adding the following logic inside `MethodSignatureComparer.EqualSignatureTypes`:

https://github.com/castleproject/Core/blob/323c03fe0e72fd26b94cde8a3f817905c89e5a39/src/Castle.Core/DynamicProxy/Generators/MethodSignatureComparer.cs#L132-L139

But before code execution gets there, it has to go through several other checks, amongst them this one here:

https://github.com/castleproject/Core/blob/323c03fe0e72fd26b94cde8a3f817905c89e5a39/src/Castle.Core/DynamicProxy/Generators/MethodSignatureComparer.cs#L93-L96

This is why your scenario with a generic record base class fails: DynamicProxy compares the signatures of the `<Clone>$` methods from `MyBaseGenericRecord<T>` and `MyDerivedGenericRecord`; and because one of those types is generic while the other is not, the above condition is met and we never get to the check for covariant returns. DynamicProxy then thinks that there are two distinct `<Clone>$` methods and tries to implement them both... which is what causes Reflection Emit to throw.

**Comment by CesarD** [comment]
Thanks a lot for taking care of this one!! <3

**Comment by stakx** [comment]
@CesarD, FYI, I've just pushed Moq 4.18.4 to NuGet, which now uses Castle.Core 5.1.1, which includes a fix for your issue.

**Comment by CesarD** [comment]
Thank you so much!!! 👏🏼🫶🏼
