### ISSUE TITLE
Mono: runtime crash with DynamicProxy: Assertion at reflection.c:2745, condition 'field' not met

### ISSUE THREAD

**Issue by floydpink** [castleproject/Core#72]
As discussed on the mailing list, below is a console app that is compiling well on Mac but crashing Mono at runtime. It is compiling and running fine on .NET/Windows.

Here is the repo that has this file as part of a ready to repro solution: https://github.com/floydpink/Crash-Repro

And the output along with the stack trace and the crash dump from Xamarin Studio: http://paste.ubuntu.com/9376527/

(The larger project where I am trying to get this for AOP logging is [this one](https://github.com/flickr-downloadr/flickr-downloadr-gtk/tree/dynamic-proxy))

Thanks!

``` csharp
using System;
using System.Linq.Expressions;
using Castle.DynamicProxy;
using StructureMap;

namespace Crash_Repro {
    public class Program {
        private static void Main(string [] args) {
            // Initialize the StructureMap IoC container with DynamicProxy based interception for logging
            Bootstrapper.Initialize();

            // Initialize the view and get something done
            IView view = new MyView();
            view.PrintNameAndAge();

            Console.ReadKey(true);
        }
    }

    #region Dummy View

    public interface IView {
        bool NeedFemaleName { get; }
        void PrintNameAndAge();
    }

    public class MyView : IView {
        private readonly ILogic _logic;

        public MyView() {
            _logic = Bootstrapper.GetLogic<IView, ILogic>(this);
        }

        public bool NeedFemaleName { get { return false; } }

        public void PrintNameAndAge() {
            Console.WriteLine("Name: {0} | Age: {1}", _logic.GetName(), _logic.GetAge());
        }
    }

    #endregion

    #region Logic - depends on Service

    public interface ILogic {
        string GetName();
        int GetAge();
    }

    public class MyLogic : ILogic {
        private readonly IService _service;
        private readonly IView _view;

        public MyLogic(IView view, IService service) {
            _view = view;
            _service = service;
        }

        public string GetName() {
            return _view.NeedFemaleName ? _service.GetFemaleName() : _service.GetMaleName();
        }

        public int GetAge() {
            return _service.GetAge();
        }
    }

    #endregion

    #region Service

    public interface IService {
        string GetMaleName();
        string GetFemaleName();
        int GetAge();
    }

    public class MyService : IService {
        public string GetMaleName() {
            return "John Doe";
        }

        public string GetFemaleName() {
            return "Jane Doe";
        }

        public int GetAge() {
            return 42;
        }
    }

    #endregion

    #region Dynamic Proxy

    public class DynamicProxy {
        public static Expression<Func<T, T>> MyInterceptorFor<T>() {
            return s => CreateInterface(typeof (T), s);
        }

        private static T CreateInterface<T>(Type interfaceType, T concreteObject) {
            return (T) new ProxyGenerator().CreateInterfaceProxyWithTargetInterface(interfaceType, concreteObject, new MyInterceptor());
        }
    }

    public class MyInterceptor : IInterceptor {
        public void Intercept(IInvocation invocation) {
            Console.WriteLine("Called {0}::{1}\n", invocation.TargetType.Name, invocation.Method.Name);
            invocation.Proceed();
        }
    }

    #endregion

    #region StructureMap Boostrapper

    public static class Bootstrapper {
        private static readonly Container _container = new Container();

        public static void Initialize() {
            _container.Configure(c => {
                                     c.For<ILogic>().DecorateAllWith(DynamicProxy.MyInterceptorFor<ILogic>()).Use<MyLogic>();
                                     c.For<IService>().DecorateAllWith(DynamicProxy.MyInterceptorFor<IService>()).Use<MyService>();
                                 });
        }

        public static TLogic GetLogic<TView, TLogic>(TView view) {
            return _container.With(view).GetInstance<TLogic>();
        }
    }

    #endregion
}
```

**Comment by jonorossi** [comment]
Confirmed this still crashes the mono runtime with Mono 4.0.1. Will need to get a smaller repro unit test into the mono-support branch to debug it easier.

**Comment by floydpink** [comment]
In an attempt to debug [the probable failing statement](https://github.com/castleproject/Core/blob/mono-support/src/Castle.Core/DynamicProxy/Generators/Emitters/SimpleAST/FieldReference.cs#L87) (as indicated by the [crash log](http://paste.ubuntu.com/9376527/)), I inlined the `Castle.Core` project into the crashing solution using these two commits: https://github.com/floydpink/Crash-Repro/compare/master...debug-deeper-into-mono

No functional changes were made there - here is a summary of what all was done
1. Copy pasted the `src\Castle.Core` folder adjacent to the crash-repro project and added `Castle.Core` as a project dependency (rather than a Nuget package)
2. Inlined the necessary targets from `Castle.Common.Targets` into `Castle.Core.csproj`
3. Disabled the compiler setting for `Treat warnings as errors` on `Castle.Core.csproj`

And this made the crash disappear on both Mac and Ubuntu running Mono 4.0.1 :confused:
So the latest [on this branch](https://github.com/floydpink/Crash-Repro/tree/debug-deeper-into-mono) prints the same console output as Windows does with the Nuget version of `Castle.Core.dll`

**Could this be because after making a project dependency, `Castle.Core` itself is being compiled with Mono rather than the Nuget package being built (presumably) on Windows against .NET?**

**Comment by jonorossi** [comment]
mcs could be generating different IL to csc, however it still crashed for me on OSX using the built binary from compiling with Mono 4.0.1. Could you try the Castle.Core.dll that the Linux build agent is outputting:

http://builds.castleproject.org/viewType.html?buildTypeId=Core_MonoSupportMono

**Comment by floydpink** [comment]
Could repro the crash with the Castle.Core.dll downloaded from the latest build (number 41) there - so it cannot be mcs vs. csc.

Looks like the couple of commits that I made to bring the Castle.Core project inline into the Crash-Repro solution might have the answer to this - shall spend some more time on it.

**Comment by pshomov** [comment]
+1 I have a feeling this is connected to my crashes of Moq and NSubstitute on OS X

**Comment by kkozmic** [comment]
Did you get any more clarity on this issue @floydpink ?

**Comment by floydpink** [comment]
@kkozmic - I haven't been able to find time to look into this and so do not have anything new.

**Comment by Worthaboutapig** [comment]
I have acquired that same problem though whether the cause is the same, I don't know.  If I run my app in Win10 from VS2015 using the NuGet package, all is fine.  If I then deploy the same (with Windows-built dlls) onto Mono (4.5.4-1-ARCH , mono version 4.4.0), I get the same stack trace when I try to create a proxy for a generic type.
If I inline the current master of Castle.Core, it still occurs... however, if I simply turn off the dll signing on Castle-Core, the problem goes away- I deploy and everything's hunky-dory.

Any thoughts?

I'll try to get some detail on exactly what's failing, but I don't use signed assemblies, hence discovering a 'solution'.  I'll sign my stuff and see if I can get some contextual output.

**Comment by Worthaboutapig** [comment]
I'm thinking mine may be different, I've managed to isolate the part that is failing and it's when this AssignStatement is emitted: [ImplementChangeProxyTarget:changeInvocationTarget.CodeBuilder.AddStatement](https://github.com/castleproject/Core/blob/master/src/Castle.Core/DynamicProxy/Generators/InvocationTypeGenerator.cs#L308)

I can't see why, there's nothing obviously wrong.

@floydpink For me this is when I change the proxy invocation target.  Are you doing this?

Also, although the assertion failure appears to be the same, it's occurring on a different line. in reflection.c.

Ideally, I'd like to debug into the Mono source for this...

**Comment by Worthaboutapig** [comment]
I've looked into this further and can't see anything wrong directly.  I thought it might be a `null` `FieldHandle` for the `__target`, but it isn't.

However, the signed/ non-signed got me thinking.  Currently I reckon there must be a difference in the way the IL is generated/ security-checked between the Mono runtime and the Microsoft runtime.  If I run my code with a signed Castle Core, I get the assert failure, if I turn off the signing, and this is all I do, then everything flies by, no problem.

So, I'm wondering if there is a problem generating IL for a proxied-type which isn't in a signed DLL?  Though I'm guessing most people don't sign their DLLs?  My proxied type is a generic class, derived from a generic interface.  This proxy base class is in a different assembly from the code that calls Castle.Core proxy generation and a different assembly from the executing assembly.  None of myassemblies is signed.

I don't have any special permissions, just what's setup up automatically in the AppDomain.

It seems to me that there's something fishy going on with permissions, as evidenced by the signed/ not signed behaviour.  Having a look at the System.Reflection.Emit documentation, there are a number of security issues to handle.

I think I've done as much as I can, I'll continue running with a non-signed version and would be interested in any feedback @floydpink @kkozmic

**Comment by floydpink** [comment]
@Worthaboutapig - I haven't been doing anything with the project that needed DynamicProxy in quite some time. But if my memory serves me correctly, I wasn't doing any signing of my assemblies when I created the original issue.

If you get a chance, do you mind cloning [this repo](https://github.com/floydpink/Crash-Repro) that I had set up as a way to reproduce the issue specific to my set up?

:+1: for all your comments on this one.

**Comment by Worthaboutapig** [comment]
@floydpink I'm writing a database that relies entirely on it :) I'll take a look at your repo and see what I get.

**Comment by Worthaboutapig** [comment]
@floydpink: Ok, I've managed to look at it now and the good news is that the Crash-Repro exhibits the same behaviour and follows my analysis exactly:) Not that it gets us anywhere closer to a solution or the actual cause.

I forked your repo, compiled as-is and it runs fine on Windows/VS2015, but falls over on Mono in Arch (the same machine as I've been experiencing problems on), so this is reproducible, which is good.

Next step was to test my theory.  Perhaps you could try this to verify my results?

1. Take your repo and remove the Castle NugGet package and replace it with the Castle project from source. [Castle Core](https://github.com/castleproject/Core)

2. In the Castle Core project properties, turn off signing.

3. Clean the project, add a project reference to Castle Core in Crash-Repro and rebuild.

4. Test on Windows and deploy to Mono and test.  This should now succeed on both platforms.

Assuming this works, further evidence is to run the repro all signed:

1. Turn back on the Castle Core signing (leaving the source project, not NuGet)

2. Replace the two structuremap projects with the source ([structuremap](https://github.com/structuremap/structuremap)) (the NuGet packages aren't signed).

3. In the structuremap projects turn on signing with the provided key.

4. In the Crash-Repro project create a key (without a password is better if you want to test it with MonoDevelop) and turn on signing.

5.  Clean and rebuild all and run the tests again.  It should now run fine on both platforms.

Further looking at this, although your code doesn't change the proxy target, the default proxy creator allows the changing of the proxy target, so the code for changing the proxy target in the interceptor is generated anyway- and that's where it's failing, exactly the same as my code. (I've even commented out the failing line and it works fine (see [Failing assign statement](https://github.com/castleproject/Core/blob/076c894819a3910e15ccfab0e37e0727afa3894d/src/Castle.Core/DynamicProxy/Generators/InvocationTypeGenerator.cs#L308)), so you could test that too).

This suggests to me that there is some security shenanigans going on, as all signed works fine and no signed works fine, it also works with Crash-Repro signed, but not Castle Core/ StructureMap.  It seems to be this particular assign statement that isn't allowed (when generating the IL) for some reason when you're trying to create a proxy of a type that is referenced in an assembly with higher restrictions than the `Castle.Core` assembly that generates the proxy.
  
However, I don't really know much about the intricacies of trust scenarios.  The specific problem is the assert of the `FieldHandle` is failing in the `StoreReference` in the `AssignStatement` when not signed, this is the case for your repro and my project.  However, I'm not really sure how to investigate the causes of this and it seems a bit strange that other people haven't run into the problem- unless very few people have run `DynamicProxy` on Mono/Linux, which I suppose is perfectly possible.  As I said before, the MS documentation talks quite a lot of the security issues around IL emitting, so I guess I could start there and read up.  It looks like this will require some dedication to figure out (but I hate to not let these things be solved ;) ).  I guess either Mono is being too restrictive/ checking something that doesn't need checking, or the MS code is too lax... Still, as far as I can see from debugging, there's nothing different about this field reference from the other ones that pass, and debugging this is not going to be easy, as it's C code in the Mono framework.

I guess I could trying compiling Mono on Windows and seeing if the problem is exhibited there and whether I can debug the repro and attach to the compiled mono to break into it to get more debugging info, as the VS debugging experience is superior to MonoDevelop.

Do you know someone, or know someone who knows someone who might have some idea of what could be going wrong here?

If you could confirm my results with your repro, that'd be helpful, I'll read up on signing/ IL emitting.

**Comment by jonorossi** [comment]
@Worthaboutapig I assume when you refer to "signing" you are referring to "strong name signing" not "code signing".

My advice would be to put together the smallest possible repro using just the .NET reflection classes without DynamicProxy or StructureMap. The Mono runtime guys are usually pretty responsive getting runtime bugs like this resolved if they are provided a clear and minimal repro.

**Comment by Worthaboutapig** [comment]
@jonorossi Yes, 'strong name' signing, sorry I wasn't clear about that.  Thanks for the advice, I'll see if I can put together a minimal example using just the mono source.

**Comment by jonorossi** [comment]
Moving this issue out of v4.0.

**Comment by stakx** [comment]
@floydpink, @pshomov, @Worthaboutapig, @jonorossi - This issue has lain dormant for a while.

While I can reproduce this problem reported here using an older version of Mono (4.2.1.102) running on Ubuntu, it is gone when using the current version of Mono (5.12.0.301).

I am therefore assuming that whatever caused the issue has since been fixed.

May we close this issue, or is anyone still having that problem, even after upgrading to a recent version of Mono?

**Comment by jonorossi** [comment]
> While I can reproduce this problem reported here using an older version of Mono (4.2.1.102) running on Ubuntu, it is gone when using the current version of Mono (5.12.0.301).

If the problem is gone on a newer Mono then yes, let's close it. Great to hear Mono is fixed.
