### ISSUE TITLE
Interceptor Selectors under CreateClassProxy are provided a System.RuntimeType rather than a System.Type

### ISSUE THREAD

**Issue by MadillJ** [castleproject/Core#74]
When writing an implementation of an IInterceptorSelector that is dependent on the proxied type I have found that the type argument given to the selector is incorrect; it is being given System.RunTimeType.

I have looked through the code a fair bit but unfortunately have no experience with code emitters so could not pinpoint the source, however the accepted answer on [this SO question](http://stackoverflow.com/questions/19011818/using-castle-windsor-to-register-an-interceptor-for-only-the-derived-class-not) provides a good minimal reproduction of the issue.

**Comment by jonorossi** [comment]
Thanks for the details especially those in the SO question.

I've worked out this defect only affects `CreateClassProxy` and can confirm that it was [introduced](https://github.com/castleproject/Core/commit/b2014da1a43dd324146555e74e0799cc961c0d6a) in 3.2.0 under [DYNPROXY-175](https://github.com/castleproject/castle-youtrack-export/blob/master/DYNPROXY/DYNPROXY-175.xml), which is why 3.1.0 works as you reported.

We don't currently have any unit tests to verify the `type` parameter which is why this regression unfortunately has occurred.

This is what `type` is for each generator method:
* `CreateClassProxy`: currently a `System.RuntimeType` because `ClassProxyTargetContributor` [passes through a `TypeTokenExpression`](https://github.com/castleproject/Core/blob/master/src/Castle.Core/DynamicProxy/Contributors/ClassProxyTargetContributor.cs#L88)
* `CreateClassProxyWithTarget`: a `System.Type` for the target
* `CreateInterfaceProxyWithTarget`: a `System.Type` for the target
* `CreateInterfaceProxyWithTargetInterface`: a `System.Type` for the target
* `CreateInterfaceProxyWithoutTarget`: `null`, there is no target

Unfortunately we've also got a mismatch between behaviour and documented behaviour via XML comments. `type` is implemented as target type, and `method` is implemented as documented, you can get the type declaring the method to intercept via `method.DeclaringType`.
```
public interface IInterceptorSelector
{
    /// <summary>
    ///   Selects the interceptors that should intercept calls to the given <paramref name = "method" />.
    /// </summary>
    /// <param name = "type">The type declaring the method to intercept.</param>
    /// <param name = "method">The method that will be intercepted.</param>
    /// <param name = "interceptors">All interceptors registered with the proxy.</param>
   ...
    IInterceptor[] SelectInterceptors(Type type, MethodInfo method, IInterceptor[] interceptors);
}
```

I'll look at getting a set of unit tests added and the fix.

**Comment by kkozmic** [comment]
Has this issue progressed any further?

**Comment by jonorossi** [comment]
I think I've got a patch someone in my Windows VM with a hacky fix from January, but never got back to it.
